const PRODUCTS = [

  // ── KUNSTSTOFF ──────────────────────────────────────────────────────────────

  {
    id: 'ideal-8000',
    name: 'IDEAL 8000',
    tagline: 'Das Passivhaus-Fenster',
    category: 'Kunststoff',
    badge: 'Bestseller',
    image: 'images/ideal-8000.png',
    imageContain: true,
    gallery: [
      'images/ideal-8000.png',
    ],
    shortDesc: 'Höchste Energieeffizienz für Neubauten und anspruchsvolle Sanierungen. Passivhaus-geeignet, RC2 Einbruchschutz, 6 Kammern, 3 Dichtungen.',
    description: 'Die ENERGIESPARENDEN Fenster im Fenstersystem IDEAL 8000 sind eine Kombination modernster technischer Lösungen, die Wärme, Ruhe und Sicherheit garantieren. Diese Fenster sind für Investoren konzipiert, die an sicherem, energieeffizientem und passivem Bauen interessiert sind.\n\nMit einem Uw-Wert von nur 0,76 W/m²K erfüllt das IDEAL 8000 alle Anforderungen des Passivhausstandards und bietet gleichzeitig zertifizierten Einbruchschutz der Klasse RC2. Durch die 6-Kammer-Konstruktion und 3 umlaufende Dichtungen erreicht das Profil eine Bautiefe von 85 mm – für optimale Wärmedämmung auch bei extremen Klimabedingungen.\n\nMit über 38 verfügbaren Dekorfolien lässt es sich individuell an jede Architektursprache anpassen. Ideal für Neubauten, Passivhäuser und hochwertige Sanierungen – wenn keine Kompromisse beim Energiestandard gemacht werden dürfen.',
    specs: [
      { label: 'Uw-Wert', value: '0,76* W/m²K' },
      { label: 'Bautiefe', value: '85 mm' },
      { label: 'Kammern', value: '6' },
      { label: 'Dichtungen', value: '3 umlaufend' },
      { label: 'Einbruchschutz', value: 'RC2' },
      { label: 'Standard', value: 'Passivhaus' },
      { label: 'Dekore', value: '38 Sorten' },
      { label: 'Verglasung', value: '3-fach' },
    ],
    specsNote: '* Der Uw-Wert betrifft das Referenzfenster mit dem Maß 1230×1480 mm, der 3-fach Verglasung mit warmer Kante und Ug-Wert 0,5 W/m²K.',
    features: [
      'Passivhaus-geeignet (zertifiziert)',
      'Einbruchschutz Klasse RC2',
      '6 Kammern, 3 umlaufende Dichtungen',
      'Bis zu 38 Dekorfolien verfügbar',
      'CE-zertifiziert',
      'Für Neubau und Sanierung geeignet',
    ],
    badges: [
      { type: 'german-market', label: 'Geeignet für den deutschen Markt' },
      { type: 'passivhaus', label: 'Passivhaus' },
      { type: 'rc2', label: 'RC2 Einbruchschutz' },
    ],
    variants: [
      { name: 'Classic Line', color: '#ffffff', border: '#d1d5db', profile: '180×05' },
      { name: 'Standard', color: '#7B4A2D', border: '#7B4A2D', profile: '180×05' },
      { name: 'Anthrazit', color: '#3C3C3C', border: '#3C3C3C', profile: '180×20' },
    ],
  },

  {
    id: 'ideal-7000',
    name: 'IDEAL 7000',
    tagline: 'Premium ENERGO-Fenster',
    category: 'Kunststoff',
    badge: 'Energie A+',
    image: 'images/produkt-2-ideal7000.png',
    gallery: [
      'images/produkt-2-ideal7000.png',
      'images/produkt-2-ideal7000-2.png',
    ],
    shortDesc: 'Premiumfenster ENERGO auf Basis des IDEAL 7000-Profils. RC2 Einbruchschutz, 6 Kammern, 85 mm Bautiefe – ideal für moderne Einfamilienhäuser.',
    description: 'Premiumfenster ENERGO, die auf Basis des IDEAL 7000-Profils hergestellt werden, sind ein Beispiel für die Kombination der Eigenschaften von Profil und Isolierglas, um Fenster mit sehr niedrigem Wärmedurchgangskoeffizienten zu schaffen. Vor allem in modernen Einfamilienhäusern ist dies eine hervorragende Wahl.\n\nMit einem Uw-Wert von 0,79 W/m²K, 6 Kammern und 85 mm Bautiefe bietet das IDEAL 7000 hervorragende Wärmedämmeigenschaften bei gleichzeitigem Einbruchschutz der Klasse RC2. Das 3-fach Glaspaket sorgt für optimale Schall- und Wärmedämmung.\n\nMit bis zu 38 Dekorfolien lässt sich das Profil individuell an jede Architektursprache anpassen – in Standardweiß oder mit anthrazitgrauem Kern.',
    specs: [
      { label: 'Uw-Wert', value: '0,79* W/m²K' },
      { label: 'Bautiefe', value: '85 mm' },
      { label: 'Kammern', value: '6' },
      { label: 'Dichtungen', value: '2 umlaufend' },
      { label: 'Einbruchschutz', value: 'RC2' },
      { label: 'Glaspaket', value: '3-fach' },
      { label: 'Dekore', value: '38 Sorten' },
      { label: 'Zertifizierung', value: 'CE' },
    ],
    specsNote: '* Der Uw-Wert betrifft das Referenzfenster mit dem Maß 1230×1480 mm und der 2-fach Verglasung mit warmer Kante und Ug-Wert 1,1 W/m²K.',
    features: [
      'Einbruchschutz Klasse RC2',
      '6 Kammern, 2 umlaufende Dichtungen',
      '85 mm Bautiefe',
      '3-fach Glaspaket',
      'Bis zu 38 Dekorfolien verfügbar',
      'CE-zertifiziert',
      'Ideal für moderne Einfamilienhäuser',
    ],
    badges: [
      { type: 'rc2', label: 'RC2 Einbruchschutz' },
      { type: 'ce', label: 'CE-zertifiziert' },
    ],
    variants: [
      { name: 'Standard', color: '#ffffff', border: '#d1d5db', profile: '170×02 / 170×20' },
      { name: 'Anthrazitgrauer Kern', color: '#3C3C3C', border: '#3C3C3C', profile: '170×02 / 170×20' },
    ],
  },

  {
    id: 'neo',
    name: 'NEO – New Look',
    tagline: 'Zeitlos kubisches Design',
    category: 'Kunststoff',
    badge: 'Design',
    image: 'images/produkt-3-neo.png',
    gallery: [
      'images/produkt-3-neo.png',
      'images/produkt-3-neo-2.png',
    ],
    shortDesc: 'Zeitloses kubisches Design mit symmetrischer Profilform. ift Rosenheim zertifiziert, 6 Kammern, 76 mm Bautiefe.',
    description: 'Die NEW LOOK Fenster sind ein äußerst attraktives Designangebot für Kunden, die Wert auf einen zeitlosen Stil legen. Die symmetrische, kubistische Form ist das charakteristische Merkmal der Fenster im NEO-System. Die NEW LOOK Fenster sind ein schlichtes und schönes Design für jedes Zuhause. Sie schaffen eine harmonische Verbindung zwischen Innen- und Außenelementen, wodurch der Raum heller und einladender wirkt.\n\nMit einem Uw-Wert von 0,78 W/m²K und einer Bautiefe von 76 mm bietet das NEO hervorragende Wärmedämmeigenschaften bei schmalem Profil. Das Profil ist mit 2- oder 3-fach Glaspaket sowie 2 oder 3 Dichtungen erhältlich und passt sich so optimal an unterschiedliche Anforderungen an.\n\nMit bis zu 38 Dekorfolien lässt sich das NEO individuell gestalten – ein schlichtes und schönes Design für jedes Zuhause.',
    specs: [
      { label: 'Uw-Wert', value: '0,78* W/m²K' },
      { label: 'Bautiefe', value: '76 mm' },
      { label: 'Kammern', value: '6' },
      { label: 'Dichtungen', value: '2 o. 3' },
      { label: 'Glaspaket', value: '2- o. 3-fach' },
      { label: 'Dekore', value: '38 Sorten' },
      { label: 'Zertifizierung', value: 'ift Rosenheim + CE' },
    ],
    specsNote: '* Der Uw-Wert betrifft das Referenzfenster NEO MD mit dem Maß 1230×1480 mm und der 2-fach Verglasung mit warmer Kante und Ug-Wert 1,0 W/m²K.',
    features: [
      'Symmetrisches, kubisches Profil',
      'Harmonische Verbindung Innen- und Außenbereich',
      '6 Kammern, 76 mm Bautiefe',
      '2- oder 3-fach Glaspaket wählbar',
      '2 oder 3 Dichtungen',
      'Bis zu 38 Dekorfolien',
      'ift Rosenheim zertifiziert',
      'CE-zertifiziert',
    ],
    badges: [
      { type: 'ift', label: 'ift Rosenheim zertifiziert' },
      { type: 'ce', label: 'CE-zertifiziert' },
    ],
    variants: [
      { name: 'NEO MD', color: '#ffffff', border: '#d1d5db', profile: '160×07 / 160×20' },
      { name: 'NEO AD', color: '#C4A882', border: '#C4A882', profile: '160×01 / 160×20' },
    ],
  },

  {
    id: 'ideal-4000',
    name: 'IDEAL 4000',
    tagline: 'Universal ECO-Fenster',
    category: 'Kunststoff',
    image: 'images/produkt-4-ideal4000.png',
    gallery: [
      'images/produkt-4-ideal4000.png',
      'images/produkt-4-ideal4000-2.png',
    ],
    shortDesc: 'UNIVERSAL ECO-Fenster in klassischer und runder Profillinie. Perfekte Balance aus Ökonomie und Ökologie – ift Rosenheim zertifiziert.',
    description: 'UNIVERSAL ECO-Fenster, basierend auf dem IDEAL 4000 Profil, bieten die perfekte Balance zwischen klassischem Design und den funktionalen Aspekten modernster Bautechnologien. Die UNIVERSAL ECO-Fenster, die in zwei Profiltypen (klassisch und rund) sowie in Drei- und Doppelglaspaketen angeboten werden, gewährleisten die optimale Kombination von Ökonomie und Ökologie.\n\nMit 5 Kammern, 2 Dichtungen und einer Bautiefe von 70 mm ist das IDEAL 4000 eine solide und langlebige Wahl für Wohngebäude, Mehrfamilienhäuser und Sanierungsprojekte. Die ift Rosenheim-Zertifizierung belegt die geprüfte Qualität nach europäischem Standard.\n\nMit bis zu 38 Dekorfolien lässt es sich individuell gestalten.',
    specs: [
      { label: 'Uw-Wert', value: '1,28* W/m²K' },
      { label: 'Bautiefe', value: '70 mm' },
      { label: 'Kammern', value: '5' },
      { label: 'Dichtungen', value: '2 umlaufend' },
      { label: 'Glaspaket', value: '2- o. 3-fach' },
      { label: 'Dekore', value: '38 Sorten' },
      { label: 'Zertifizierung', value: 'ift Rosenheim + CE' },
    ],
    specsNote: '* Der Uw-Wert betrifft das Referenzfenster mit dem Maß 1230×1480 mm und der 2-fach Verglasung mit warmer Kante und Ug-Wert 1,1 W/m²K.',
    features: [
      '5 Kammern, 70 mm Bautiefe',
      '2 umlaufende Dichtungen',
      '2- oder 3-fach Glaspaket wählbar',
      'Classic Line und Round-Line verfügbar',
      'Bis zu 38 Dekorfolien',
      'ift Rosenheim zertifiziert',
      'CE-zertifiziert',
    ],
    badges: [
      { type: 'ift', label: 'ift Rosenheim zertifiziert' },
      { type: 'ce', label: 'CE-zertifiziert' },
    ],
    variants: [
      { name: 'Classic Line', color: '#ffffff', border: '#d1d5db', profile: '140×01 / 140×20' },
      { name: 'Round-Line', color: '#f3f4f6', border: '#d1d5db', profile: '140×01 / 140×22' },
    ],
  },

  {
    id: 'ideal-5000',
    name: 'IDEAL 5000',
    tagline: 'Das vielseitige Mittelklasse-Fenster',
    category: 'Kunststoff',
    badge: 'Beliebt',
    image: 'images/produkt-5-ideal5000.png',
    gallery: [
      'images/produkt-5-ideal5000.png',
      'images/produkt-5-ideal5000-2.png',
    ],
    shortDesc: 'Die ausgezeichneten Dämmeigenschaften des IDEAL 5000 garantieren erstklassigen Wohnkomfort. ift Rosenheim zertifiziert, 5 Kammern, 70 mm Bautiefe.',
    description: 'Die ausgezeichneten Dämmeigenschaften des IDEAL 5000 garantieren erstklassigen Wohnkomfort. Die hochwertigen Profilsysteme von ALUPLAST gewährleisten zudem hervorragenden Einbruchschutz und somit ein beruhigendes Maß an Sicherheit.\n\nMit 5 Kammern, 3 umlaufenden Dichtungen und einer Bautiefe von 70 mm bietet das IDEAL 5000 eine solide und bewährte Lösung für Wohngebäude, Mehrfamilienhäuser und Sanierungsprojekte. Das 2- oder 3-fach Glaspaket ist frei wählbar.\n\nDas Profil ist in 5 hochwertigen Folienvarianten erhältlich – von klassisch Weiß über Golden Eiche bis hin zu modernem Jetblack Tiefschwarz.',
    specs: [
      { label: 'Uw-Wert', value: '1,23* W/m²K' },
      { label: 'Bautiefe', value: '70 mm' },
      { label: 'Kammern', value: '5' },
      { label: 'Dichtungen', value: '3 umlaufend' },
      { label: 'Glaspaket', value: '2- o. 3-fach' },
      { label: 'Dekore', value: '5 Sorten' },
      { label: 'Zertifizierung', value: 'ift Rosenheim + CE' },
    ],
    specsNote: '* Wärmedämmungskoeffizient eines Fensters Referenzabmessungen 1230×1480 mm, unter Verwendung einer Glasscheibe mit einem heißen Rahmen mit dem Koeffizienten Ug=1,1 W/m²K 4/16/4.',
    features: [
      '5 Kammern, 70 mm Bautiefe',
      '3 umlaufende Dichtungen',
      '2- oder 3-fach Glaspaket wählbar',
      '5 Foliensorten: Weiß, Golden Eiche, Anthrazit, Sandgrau, Jetblack',
      'ift Rosenheim zertifiziert',
      'CE-zertifiziert',
    ],
    badges: [
      { type: 'ift', label: 'ift Rosenheim zertifiziert' },
      { type: 'ce', label: 'CE-zertifiziert' },
    ],
    variants: [
      { name: 'Weiss Glatt', color: '#ffffff', border: '#d1d5db', profile: '150×02 / 150×20' },
      { name: 'Golden Eiche', color: '#8B5E2A', border: '#8B5E2A', profile: '150×02 / 150×20' },
      { name: 'Anthrazit Sandgrau', color: '#6B7280', border: '#6B7280', profile: '150×02 / 150×20' },
      { name: 'Sandgrauer Quarz', color: '#9CA3AF', border: '#9CA3AF', profile: '150×02 / 150×20' },
      { name: 'Jetblack Tiefschwarz', color: '#111827', border: '#111827', profile: '150×02 / 150×20' },
    ],
  },

  // ── HEBE-SCHIEBE ────────────────────────────────────────────────────────────

  {
    id: 'hst',
    name: 'HST Hebeschiebetür',
    tagline: 'Panoramablick ohne Kompromisse',
    category: 'Hebe-Schiebe',
    badge: 'Passivhaus',
    image: 'images/produkt-6-hst.png',
    gallery: [
      'images/produkt-6-hst.png',
      'images/produkt-6-hst-2.png',
    ],
    shortDesc: 'Die HST Hebeschiebetür bietet komfortable Verbindung zwischen Innen und Terrasse. Passivhaus-geeignet, Breiten bis 6,50 m, flache Schwelle.',
    description: 'Die Verwendung von HST-Hebeschiebetüren bietet eine ideale Lösung für alle, die eine komfortable Verbindung zwischen Innenraum und Terrasse wünschen und gleichzeitig von einem Panoramablick durch großzügige Glasflächen profitieren möchten. HST-Terrassentüren zeichnen sich durch ihre großzügigen Abmessungen aus, die die Herstellung von Verglasungen mit einer Breite von bis zu sechseinhalb Metern ermöglichen.\n\nDieses System ermöglicht die Konstruktion von Türen in erweiterten Abmessungen. Innerhalb dieses Systems kann die Breite dieser Türen beeindruckende 6,5 Meter erreichen. Dank spezieller Mechanismen lassen sich diese mühelos verschieben. HST-Türen sind zudem mit einer flachen Schwelle ausgestattet, und auf Wunsch des Kunden kann eine spezielle Bremse hinzugefügt werden.',
    specs: [
      { label: 'Uw-Wert', value: '0,71* W/m²K' },
      { label: 'Tauglich', value: 'Passivhaus' },
      { label: 'Bautiefe', value: '70 mm' },
      { label: 'Rahmentiefe', value: '85 mm' },
      { label: 'Max. Höhe', value: '2.700 mm' },
      { label: 'Max. Breite', value: '6.500 mm' },
      { label: 'Dekore', value: '38 Sorten' },
      { label: 'Zertifizierung', value: 'CE' },
    ],
    specsNote: '* Der Uw-Wert für eine Hebe-Schiebe-Tür HST Premium mit den Maßen 4000×2300 mm und einer Verglasung mit einem Ug-Wert von 0,5 W/m²K beträgt 0,71 W/m²K.',
    features: [
      'Passivhaus-geeignet',
      'Breiten bis 6.500 mm, Höhen bis 2.700 mm',
      'Bautiefe 70 mm, Rahmentiefe 85 mm',
      'Flache barrierefreie Schwelle',
      'Mühelos verschiebbar dank spezieller Mechanismen',
      'Optionale Bremse auf Kundenwunsch',
      '38 Dekorfolien',
      'CE-zertifiziert',
    ],
    badges: [
      { type: 'passivhaus', label: 'Passivhaus' },
      { type: 'ce', label: 'CE-zertifiziert' },
    ],
    variants: [
      { name: 'HST Premium', color: '#ffffff', border: '#d1d5db', profile: '' },
      { name: 'HST Basic', color: '#f3f4f6', border: '#d1d5db', profile: '' },
      { name: 'HST 85 Fixframe', color: '#e5e7eb', border: '#d1d5db', profile: '' },
    ],
  },

  {
    id: 'psk',
    name: 'PSK Smart Slide Neo',
    tagline: 'Parallel-Schiebe-Kipp auf neuem Level',
    category: 'Hebe-Schiebe',
    badge: 'Neuheit',
    image: 'images/produkt-7-psk.png',
    gallery: [
      'images/produkt-7-psk.png',
      'images/produkt-7-psk-2.png',
      'images/produkt-7-psk-3.png',
      'images/produkt-7-psk-4.png',
    ],
    shortDesc: 'Terrassentüren im Schiebesystem für großflächige Verglasungen bei voller Wärmedämmung. Leichte Bedienung unabhängig von Größe und Gewicht.',
    description: 'Terrassentüren im Schiebesystem ermöglichen die Schaffung großflächiger Verglasungen, wobei gleichzeitig die volle Wärmedämmung erhalten bleibt. Unabhängig von ihrer Größe und ihrem Gewicht arbeiten die Terrassentüren im Schiebe- und Kipp-Schiebe-System effizient und sind leicht zu bedienen.\n\nDer Smart Slide Neo benötigt wenig Raum und ermöglicht die Schaffung einer breiten Durchgangsöffnung zur Terrasse. Wenn die Tür geschlossen ist, bilden der Schiebeflügel und der Festflügel eine ästhetische Linie. Die Tür verfügt über eine moderne und breite Schwelle, die vielfältige Anwendungsmöglichkeiten bietet, auch im Bereich der Renovierung.\n\nDie Variante PATIO eignet sich mit ihrer traditionellen Schwelle ideal für klassische Balkontüren.',
    specs: [
      { label: 'Bautiefe (Neo)', value: '78 mm' },
      { label: 'Rahmentiefe (Neo)', value: '154 mm' },
      { label: 'Max. Höhe (Neo)', value: '6.000 mm' },
      { label: 'Max. Breite (Neo)', value: '2.500 mm' },
      { label: 'Bautiefe (Patio)', value: '85 mm' },
      { label: 'Max. Höhe (Patio)', value: '2.300 mm' },
      { label: 'Max. Breite (Patio)', value: '1.400 mm' },
    ],
    features: [
      'Parallel-Schiebe-Kipp-Funktion',
      'Smart Slide Neo: max. 6.000 mm Höhe, 2.500 mm Breite',
      'Moderne breite Schwelle (Neo) – ideal für Renovierung',
      'Patio: klassische Schwelle für Balkontüren',
      'Schiebeflügel und Festflügel bilden ästhetische Linie',
      'Leichte Bedienung unabhängig von Größe und Gewicht',
    ],
    badges: [
      { type: 'ce', label: 'CE-zertifiziert' },
    ],
    variants: [
      { name: 'Smart Slide Neo', color: '#ffffff', border: '#d1d5db', profile: '78 mm / 154 mm Rahmen', image: 'images/produkt-7-psk.png' },
      { name: 'Patio', color: '#3C3C3C', border: '#3C3C3C', profile: '85 mm Bautiefe', image: 'images/produkt-7-psk-2.png' },
    ],
  },

  // ── HAUSTÜREN ────────────────────────────────────────────────────────────────

  {
    id: 'eingangstuer-pvc',
    name: 'Eingangstür PVC',
    tagline: 'Sicherheit, Langlebigkeit und Eleganz',
    category: 'Haustür',
    badge: 'Beliebt',
    image: 'images/produkt-8-eingangstuer-pvc.png',
    imageContain: true,
    gallery: [
      'images/produkt-8-eingangstuer-pvc.png',
    ],
    shortDesc: 'Die Haustür ist das Aushängeschild des Hauses. PVC-Profile in Premium (85 mm) und Basic (70 mm), vielfältige Paneele, verstärkte Beschläge.',
    description: 'Die Haustür ist das Aushängeschild des Hauses. Bei der Auswahl von PVC-Türen können Sie sich auf Sicherheit, Langlebigkeit und Eleganz verlassen. Starke und robuste PVC-Profile bilden die Grundlage für eine breite Palette von Paneelen, sowohl modern als auch traditionell. Verstärkte Beschläge gewährleisten langanhaltenden Nutzungskomfort.\n\nDas Profil ist in zwei Ausführungen erhältlich: PREMIUM IDEAL 7000 mit 85 mm Bautiefe für höchste Ansprüche, sowie BASIC IDEAL 4000 mit 70 mm Bautiefe als solide Einstiegslösung.\n\nDrei Füllungsvarianten stehen zur Auswahl: Beidseitige Aufsatzfüllung, Einseitige Aufsatzfüllung und Standard Einsatzfüllung – für jede Gestaltungsanforderung die passende Lösung.',
    specs: [
      { label: 'Profil Premium', value: 'IDEAL 7000 – 85 mm' },
      { label: 'Profil Basic', value: 'IDEAL 4000 – 70 mm' },
      { label: 'Füllung', value: '3 Varianten' },
      { label: 'Beschläge', value: 'Verstärkt' },
      { label: 'Material', value: 'PVC' },
    ],
    features: [
      'Premium IDEAL 7000 Profil (85 mm)',
      'Basic IDEAL 4000 Profil (70 mm)',
      'Beidseitige Aufsatzfüllung',
      'Einseitige Aufsatzfüllung',
      'Standard Einsatzfüllung',
      'Verstärkte Beschläge',
      'Modern und traditionell verfügbar',
    ],
    badges: [
      { type: 'ce', label: 'CE-zertifiziert' },
    ],
    variants: [
      { name: 'Premium IDEAL 7000', color: '#ffffff', border: '#d1d5db', profile: '85 mm' },
      { name: 'Basic IDEAL 4000', color: '#f3f4f6', border: '#d1d5db', profile: '70 mm' },
    ],
  },

  {
    id: 'alu-schiebe',
    name: 'Ziehgriffe',
    tagline: 'Design-Türgriffe für Haustüren & Eingänge',
    category: 'Zubehör',
    badge: 'Neuheit',
    image: 'images/ziehgriffe.png',
    imageContain: true,
    gallery: ['images/ziehgriffe.png'],
    shortDesc: 'Hochwertige Ziehgriffe in verschiedenen Designs – von schlicht bis architektonisch, für Haustüren, Eingänge und Schiebetüren.',
    description: 'Unsere Ziehgriffe verbinden Funktion mit Design und setzen an jeder Tür einen markanten Akzent. Das Sortiment umfasst zwölf Modelle in unterschiedlichen Formen und Oberflächen – von schlanken Rundprofilen bis zu eckigen Designgriffen.\n\nVerfügbare Modelle: Z2 B30, Z6 B30, Z8, Z2 40, Z2 30, Z2 K30, Z2 B40, Z6 BB30, Z27 40X20, Z32, Z43, Z6 W30.\n\nAlle Griffe sind aus hochwertigem Stahl gefertigt und in verschiedenen Oberflächen erhältlich – Schwarz matt, Edelstahl gebürstet und Weiß. Passend für alle gängigen Haustür- und Eingangstürsysteme.',
    specs: [
      { label: 'Material', value: 'Stahl / Edelstahl' },
      { label: 'Oberflächen', value: 'Schwarz, Edelstahl, Weiß' },
      { label: 'Modelle', value: '12 Varianten' },
      { label: 'Passend für', value: 'Haustüren, Eingänge' },
    ],
    features: [
      '12 verschiedene Griffmodelle',
      'Oberflächen: Schwarz matt, Edelstahl, Weiß',
      'Passend für alle gängigen Türsysteme',
      'Schlichte und architektonische Designs',
      'Auf Anfrage auch Sondermaße',
    ],
  },

  // ── ALUMINIUM ────────────────────────────────────────────────────────────────

  {
    id: 'alu-thermo',
    name: 'Türgriffe & Türzubehör',
    tagline: 'Komplettes Zubehörsortiment für Türen',
    category: 'Zubehör',
    badge: 'Komplettsortiment',
    image: 'images/tuergriffe-zubehoer.png',
    imageContain: true,
    gallery: ['images/tuergriffe-zubehoer.png'],
    shortDesc: 'Türgriffe, Fingerabdruckleser, Bluetooth-Tastatur, Aluminium- und Automatikschwell – alles aus einer Hand.',
    description: 'Unser Türzubehör-Sortiment bietet alles, was eine hochwertige Tür komplett macht – von klassischen Türgriffen bis zu modernen Smart-Access-Lösungen.\n\nTürgriffe: Modelle P01, P10, P04 und TG12 in verschiedenen Ausführungen – passend für alle gängigen Haustür- und Eingangstürsysteme.\n\nZutrittssysteme: Fingerabdruckleser für berührungslosen Zugang sowie Tastatur mit Code und Bluetooth für flexible Zugangskontrolle.\n\nSchwellen: Aluminiumschwelle für dauerhaften wetterfesten Abschluss sowie Automatische Schwelle für barrierefreien und zugluftfreien Eingang.',
    specs: [
      { label: 'Griffmodelle', value: 'P01, P10, P04, TG12' },
      { label: 'Zugang', value: 'Fingerprint / Bluetooth' },
      { label: 'Schwellen', value: 'Alu / Automatik' },
      { label: 'Material', value: 'Edelstahl / Aluminium' },
    ],
    features: [
      'Türgriffe P01, P10, P04, TG12',
      'Fingerabdruckleser',
      'Tastatur mit Code & Bluetooth',
      'Aluminiumschwelle',
      'Automatische Schwelle (barrierefrei)',
    ],
  },

  {
    id: 'alu-ferroline',
    name: 'Klassische Kunststofftüren',
    tagline: 'Zeitlose Haustüren in klassischer Optik',
    category: 'Haustür',
    badge: 'Klassik',
    image: 'images/klassische-kunststofftueren.png',
    imageContain: true,
    gallery: ['images/klassische-kunststofftueren.png'],
    shortDesc: 'Klassische PVC-Haustüren mit und ohne Seitenteil – in zahlreichen Designs wie Sage, Model, Bekopa, Bartonia und mehr.',
    description: 'Unsere klassischen Kunststofftüren verbinden traditionelle Eleganz mit moderner PVC-Technologie. Das umfangreiche Sortiment umfasst Modelle mit und ohne Seitenteil – für jeden Geschmack und jede Fassade.\n\nModelle ohne Seitenteil: Sage 1, Model, Bekopa, Bartonia HB, Estragon, Iris, Boronia, Calendula.\n\nModelle mit Seitenteil: Safran, Sage, Bekopa, Nandina.\n\nAlle Modelle sind in verschiedenen Dekoren erhältlich – von klassischem Holzdekor bis zu modernem Weiß. Ein komplettes Angebot an Türfüllungen finden Sie unter www.mirox.pl.',
    specs: [
      { label: 'Material', value: 'PVC / Kunststoff' },
      { label: 'Varianten', value: 'Mit / ohne Seitenteil' },
      { label: 'Modelle', value: '12 Designs' },
      { label: 'Dekore', value: 'Holz, Weiß u.v.m.' },
    ],
    features: [
      '8 Modelle ohne Seitenteil',
      '4 Modelle mit Seitenteil',
      'Holzdekore und Weiß verfügbar',
      'Klassische und moderne Designs',
      'Passend für jeden Fassadentyp',
    ],
  },

  {
    id: 'alu-harmonika',
    name: 'Moderne Kunststofftüren',
    tagline: 'Zeitgemäße Haustüren in modernem Design',
    category: 'Haustür',
    badge: 'Modern',
    image: 'images/moderne-kunststofftueren.png',
    imageContain: true,
    gallery: ['images/moderne-kunststofftueren.png'],
    shortDesc: 'Moderne PVC-Haustüren in drei Ausführungen – ohne Seitenteil, mit Seitenteil und mit doppeltem Seiten- und Oberlicht.',
    description: 'Unsere modernen Kunststofftüren setzen klare Akzente und passen perfekt zu zeitgemäßer Architektur. Das Sortiment gliedert sich in drei Konfigurationen.\n\nOhne Seitenteil: 6172-83, 6233-09, 6172-94, 6184-54 – sachliche Designs mit modernen Glasausschnitten.\n\nMit Seitenteil: Alum, Carex, Gloriosa, Irge – für breitere Eingangssituationen mit elegantem Rahmen.\n\nMit doppeltem Seiten- und Oberlicht: Dahla, Ligustr – maximale Lichtöffnung für repräsentative Eingänge.\n\nAlle Modelle sind in verschiedenen Dekoren erhältlich.',
    specs: [
      { label: 'Material', value: 'PVC / Kunststoff' },
      { label: 'Varianten', value: 'Ohne / Mit Seitenteil' },
      { label: 'Modelle', value: '10 Designs' },
      { label: 'Oberlicht', value: 'Optional verfügbar' },
    ],
    features: [
      '4 Modelle ohne Seitenteil',
      '4 Modelle mit Seitenteil',
      '2 Modelle mit Seiten- & Oberlicht',
      'Moderne Glasausschnitte',
      'Verschiedene Dekore erhältlich',
    ],
  },

  // ── HAUSTÜREN ────────────────────────────────────────────────────────────────

  {
    id: 'haustuer-pvc',
    name: 'Thermo Aluminiumfenster',
    tagline: 'Aluminium-Qualität mit höchster Wärmedämmung',
    category: 'Aluminium',
    badge: 'Passivhaus',
    image: 'images/thermo-aluminiumfenster.png',
    imageContain: true,
    shortDesc: 'Thermo Aluminiumfenster in 4 Systemvarianten – vom Passivhausstandard bis zur klassischen Wärmedämmung. Profile von ALUPROF und ALUPLAST.',
    description: 'Unsere Thermo Aluminiumfenster bieten für jeden Anspruch das passende Profil – von höchster Wärmedämmung bis zur klassischen Variante. Alle Profile sind in beliebigen RAL-Farben lieferbar und lassen sich individuell auf Ihr Bauprojekt abstimmen.\n\nDas ALUPROF MB 104 PASSIVE erreicht Passivhausstandard und setzt Maßstäbe in der Energieeffizienz. Das ALUPLAST GENESIS 90 bietet hervorragende Wärmedämmung auf modernstem Niveau. Der ALUPROF MB 86 N ist ideal für anspruchsvolle Sanierungen und Neubauten. Der ALUPROF MB 45 rundet das Sortiment als klassische Aluminium-Variante ab.\n\nAlle Systeme sind für den deutschen Markt zugelassen und CE-zertifiziert.',
    specs: [
      { label: 'System 1', value: 'ALUPROF MB 104 PASSIVE' },
      { label: 'System 2', value: 'ALUPLAST GENESIS 90' },
      { label: 'System 3', value: 'ALUPROF MB 86 N' },
      { label: 'System 4', value: 'ALUPROF MB 45' },
      { label: 'Material', value: 'Aluminium' },
      { label: 'Standard', value: 'Passivhaus (MB 104)' },
      { label: 'Farben', value: 'Alle RAL-Farben' },
      { label: 'Zulassung', value: 'CE-zertifiziert' },
    ],
    features: [
      'ALUPROF MB 104 PASSIVE – höchste Wärmedämmung, Passivhausstandard',
      'ALUPLAST GENESIS 90 – hohe Wärmedämmung',
      'ALUPROF MB 86 N – solide Wärmedämmung für Neubau & Sanierung',
      'ALUPROF MB 45 – klassische Aluminium-Variante',
      'Alle RAL-Farben verfügbar',
      'CE-zertifiziert, für deutschen Markt zugelassen',
    ],
    badges: [
      { type: 'german-market', label: 'Geeignet für den deutschen Markt' },
      { type: 'passivhaus', label: 'Passivhaus' },
    ],
  },

  {
    id: 'haustuer-genesis',
    name: 'New Design Aluminiumfenster',
    tagline: 'Architektonisch anspruchsvolle Aluminium-Lösungen',
    category: 'Aluminium',
    badge: 'Design',
    image: 'images/new-design-aluminiumfenster.png',
    imageContain: true,
    shortDesc: 'New Design Aluminiumfenster in 4 Systemvarianten – Loft, Mehr-Licht, Industrie und Balustrade. Profile von ALUPROF und ALUPLAST.',
    description: 'NEW DESIGN Aluminiumfenster sind eine Lösung, die eine Reihe spezieller Anforderungen erfüllt. Je nach Profil meistern sie erfolgreich Loft- oder Industrieinstallationsräumen. Sie können auch eine maximale Belichtung von Räumen bei gleichzeitig sehr guten technischen Strukturparametern gewährleisten.\n\nDas ALUPROF MB FERROLINE überzeugt mit seinem Loft-Fenster-Charakter und industrieller Ästhetik. Der ALUPROF MB 79 N US maximiert den Lichteinfall als "Mehr Licht"-Fenster. Das ALUPLAST MAX LIGHT DESIGN ist die ideale Wahl für Industriefenster. Der ALUPROF GLASS BARRIER schließt das Sortiment als innovatives Fenster mit integrierter Balustrade ab.\n\nAlle Profile sind CE-zertifiziert und in beliebigen RAL-Farben verfügbar.',
    specs: [
      { label: 'System 1', value: 'ALUPROF MB FERROLINE' },
      { label: 'System 2', value: 'ALUPROF MB 79 N US' },
      { label: 'System 3', value: 'ALUPLAST MAX LIGHT DESIGN' },
      { label: 'System 4', value: 'ALUPROF GLASS BARRIER' },
      { label: 'Material', value: 'Aluminium' },
      { label: 'Farben', value: 'Alle RAL-Farben' },
      { label: 'Zulassung', value: 'CE-zertifiziert' },
    ],
    features: [
      'ALUPROF MB FERROLINE – Loft-Fenster mit industriellem Charakter',
      'ALUPROF MB 79 N US – maximaler Lichteinfall',
      'ALUPLAST MAX LIGHT DESIGN – Industriefenster',
      'ALUPROF GLASS BARRIER – Fenster mit integrierter Balustrade',
      'Alle RAL-Farben verfügbar',
      'CE-zertifiziert, für deutschen Markt zugelassen',
    ],
    badges: [
      { type: 'german-market', label: 'Geeignet für den deutschen Markt' },
    ],
  },

  {
    id: 'alu-untypisch',
    name: 'Untypische Aluminiumfenster',
    tagline: 'Spezialanwendungen für Innen und Außen',
    category: 'Aluminium',
    badge: 'Speziallösung',
    image: 'images/untypische-aluminiumfenster.png',
    imageContain: true,
    shortDesc: 'Basierend auf ALUPROF-Systemen: 4 Speziallösungen für Lüftung, Drehfenster, Schieben und Rauchabzug – horizontal und vertikal verschiebbar.',
    description: 'Basierend auf ALUPROF-Systemen bieten wir eine breite Palette von Fenstern für spezielle Anwendungen im Innen- und Außenbereich von Gebäuden. Sie können horizontal und vertikal verschoben werden und verfügen über eine vertikale oder horizontale Drehachse. Diese Fenster zeichnen sich durch Ästhetik, Langlebigkeit und Funktionalität aus.\n\nDas ALUPROF SLIDER WINDOW ist als Lüfterfenster ideal für kontrollierte Belüftung. Der ALUPROF PIVOT überzeugt als elegantes Drehfenster mit zentraler Drehachse. Das ALUPROF MB SLIDE ST bietet als Schiebefenster maximale Raumnutzung. Das ALUPROF Rauchabzugsfenster sorgt für zuverlässigen Rauchabzug mit integriertem Dämpfer – ideal für gewerbliche und öffentliche Gebäude.\n\nAlle Systeme sind CE-zertifiziert und in beliebigen RAL-Farben verfügbar.',
    specs: [
      { label: 'System 1', value: 'ALUPROF SLIDER WINDOW' },
      { label: 'System 2', value: 'ALUPROF PIVOT' },
      { label: 'System 3', value: 'ALUPROF MB SLIDE ST' },
      { label: 'System 4', value: 'ALUPROF Rauchabzug' },
      { label: 'Material', value: 'Aluminium' },
      { label: 'Farben', value: 'Alle RAL-Farben' },
      { label: 'Zulassung', value: 'CE-zertifiziert' },
    ],
    features: [
      'ALUPROF SLIDER WINDOW – Lüfterfenster, horizontal verschiebbar',
      'ALUPROF PIVOT – Drehfenster mit zentraler Achse',
      'ALUPROF MB SLIDE ST – Schiebefenster für maximale Raumnutzung',
      'ALUPROF Rauchabzugsfenster mit Dämpfer',
      'Alle RAL-Farben verfügbar',
      'CE-zertifiziert, für deutschen Markt zugelassen',
    ],
    badges: [
      { type: 'german-market', label: 'Geeignet für den deutschen Markt' },
    ],
  },

  {
    id: 'alu-schiebetueren',
    name: 'Aluminium Schiebetüren',
    tagline: 'Große Flächen, fließende Übergänge',
    category: 'Aluminium',
    badge: 'Großformat',
    image: 'images/aluminium-schiebetueren.png',
    imageContain: true,
    shortDesc: 'Aluminium-Schiebetürsysteme in 4 Varianten – HST, SlideGalandage, Slide System und Multi Slide. Für großflächige Verglasungen und architektonisch anspruchsvolle Lösungen.',
    description: 'Aluminium-Schiebetürsysteme erlauben das Öffnen der Tür in ihrer vollen Höhe ohne einschränkende Systeme. Diese raumeinnehmenden Systeme ermöglichen die Gestaltung von Wintergärten und großflächigen Verglasungen. Je nach architektonischem Design können mehrere Flügel eingebaut werden, die sogar in der Wand versteckt werden können.\n\nDer ALUPROF MB-59HS ist ein HST-System mit niedriger Schwelle für barrierefreies Wohnen. Die ALUPROF MB-59 SlideGalandage verschwindet komplett in der Wand. Der ALUPROF MB-77HS HI bietet als Slide System höchste Wärmedämmung. Das ALUPROF MB-SLIDE als Multi Slide System ermöglicht mehrteilige Panoramaverglasung.\n\nAlle Systeme sind CE-zertifiziert und in beliebigen RAL-Farben verfügbar.',
    specs: [
      { label: 'System 1', value: 'ALUPROF MB-59HS' },
      { label: 'System 2', value: 'ALUPROF MB-59 SlideGalandage' },
      { label: 'System 3', value: 'ALUPROF MB-77HS HI' },
      { label: 'System 4', value: 'ALUPROF MB-SLIDE' },
      { label: 'Material', value: 'Aluminium' },
      { label: 'Farben', value: 'Alle RAL-Farben' },
      { label: 'Zulassung', value: 'CE-zertifiziert' },
    ],
    features: [
      'ALUPROF MB-59HS – HST-System mit niedriger Schwelle',
      'ALUPROF MB-59 SlideGalandage – in der Wand versteckbar',
      'ALUPROF MB-77HS HI – Slide System mit hoher Wärmedämmung',
      'ALUPROF MB-SLIDE – Multi Slide System für Panoramaverglasung',
      'Alle RAL-Farben verfügbar',
      'CE-zertifiziert, für deutschen Markt zugelassen',
    ],
    badges: [
      { type: 'german-market', label: 'Geeignet für den deutschen Markt' },
    ],
  },

  {
    id: 'alu-falltueren',
    name: 'Aluminium Falttüren',
    tagline: 'Harmonika-Lösung für Terrasse & Wintergarten',
    category: 'Aluminium',
    badge: 'Harmonika',
    image: 'images/aluminium-falltueren.png',
    imageContain: true,
    shortDesc: 'Falttüren aus Aluminium (Harmonika-Form) für Terrassen und Wintergärten. Großflächige Verglasung bei minimalem Platzbedarf im geöffneten Zustand.',
    description: 'Falttüren aus Aluminium, auch als Harmonika-Form bezeichnet, finden hauptsächlich Verwendung als Eingänge zu Terrassen oder Wintergärten. Diese technische Lösung ermöglicht die Schaffung großflächiger Verglasungen bei gleichzeitig minimalem Platzbedarf im geöffneten Zustand.\n\nHarmonikalösungen eignen sich perfekt, um den Wohnraum auch im Winter nahtlos mit einer Terrasse oder einem Garten zu verbinden. Die Falttüren bestehen aus wärmegedämmten Profilen. Je nach Bedarf können sie nach innen oder nach außen öffnende Strukturen aufweisen.\n\nCE-zertifiziert, RAL-Gütezeichen, in allen RAL-Farben verfügbar.',
    specs: [
      { label: 'Typ', value: 'Harmonika / Falttür' },
      { label: 'Material', value: 'Aluminium' },
      { label: 'Profil', value: 'Wärmegedämmt' },
      { label: 'Öffnung', value: 'Nach innen oder außen' },
      { label: 'Verglasung', value: 'Großflächig' },
      { label: 'Farben', value: 'Alle RAL-Farben' },
      { label: 'Zulassung', value: 'CE-zertifiziert' },
    ],
    features: [
      'Harmonika-Falttür für Terrassen und Wintergärten',
      'Wärmegedämmte Aluminiumprofile',
      'Öffnung nach innen oder außen möglich',
      'Minimaler Platzbedarf im geöffneten Zustand',
      'Großflächige Verglasung',
      'Alle RAL-Farben verfügbar',
      'CE-zertifiziert, RAL-Gütezeichen',
    ],
    badges: [
      { type: 'german-market', label: 'Geeignet für den deutschen Markt' },
    ],
  },

  {
    id: 'alu-eingangstueren',
    name: 'Aluminium Eingangstüren',
    tagline: 'Hohe Steifigkeit und Festigkeit bei geringem Gewicht',
    category: 'Haustür',
    badge: 'RC2',
    image: 'images/aluminium-eingangstueren.png',
    imageContain: true,
    shortDesc: 'Aluminium-Eingangstüren in 4 Systemen – Genesis 75, Imperial 800, MB 104 Passive und MB-86. Hohe Steifigkeit, geringe Dichte, sicherheitsrelevant.',
    description: 'Der Hauptvorteil von Aluminium-Türen ist die hohe Steifigkeit und Festigkeit bei gleichzeitig geringem Gewicht. Sie verhalten sich während des Gebrauchs nicht. Festigkeitsparameter sind auch für die Einbruchsicherung von Bedeutung und werden daher häufig von sicherheitsbewussten Anlegern gewählt.\n\nALUPLAST GENESIS 75 kombiniert elegantes Design mit robuster Konstruktion. Das ALUPLAST IMPERIAL 800 bietet maximale Repräsentanz für anspruchsvolle Eingangsbereiche. Der ALUPROF MB 104 PASSIVE erreicht Passivhausstandard auch bei Türen. Der ALUPROF MB-86 rundet das Sortiment als solide Standardlösung ab.\n\nAlle Systeme sind CE-zertifiziert und in beliebigen RAL-Farben verfügbar.',
    specs: [
      { label: 'System 1', value: 'ALUPLAST GENESIS 75' },
      { label: 'System 2', value: 'ALUPLAST IMPERIAL 800' },
      { label: 'System 3', value: 'ALUPROF MB 104 PASSIVE' },
      { label: 'System 4', value: 'ALUPROF MB-86' },
      { label: 'Material', value: 'Aluminium' },
      { label: 'Farben', value: 'Alle RAL-Farben' },
      { label: 'Zulassung', value: 'CE-zertifiziert' },
    ],
    features: [
      'ALUPLAST GENESIS 75 – elegante Aluminium-Eingangstür',
      'ALUPLAST IMPERIAL 800 – repräsentativer Eingang',
      'ALUPROF MB 104 PASSIVE – Passivhausstandard auch für Türen',
      'ALUPROF MB-86 – solide Standardlösung mit hoher Steifigkeit',
      'Alle RAL-Farben verfügbar',
      'CE-zertifiziert, für deutschen Markt zugelassen',
    ],
    badges: [
      { type: 'german-market', label: 'Geeignet für den deutschen Markt' },
      { type: 'passivhaus', label: 'Passivhaus (MB 104)' },
    ],
  },

  {
    id: 'aussenrollaeden',
    name: 'Außenrolläden',
    tagline: 'Sonnenschutz, Sichtschutz & Wärmedämmung',
    category: 'Zubehör',
    badge: 'Sonnenschutz',
    image: 'images/aussenrollaeden.png',
    imageContain: true,
    shortDesc: 'Außenrolläden als wichtige architektonische Elemente – in zwei Varianten: Aufsatzrolläden (RNS, RNK/E, RNK/XT) und Vorsatzrolläden (RAK/E, RAS, RAR/E).',
    description: 'Rolläden an der Außenseite sind wichtige architektonische Elemente der Gebäudeausstattung. Sie dienen in erster Linie dem Schutz des Innenraums vor Einbruch. Darüber hinaus tragen sie zur zusätzlichen Isolierung von Fenstern und Balkontüren bei. Die richtige Auswahl gewährleistet dabei jahrelang höheren thermischen Komfort und Sicherheit.\n\nAufsatzrolläden (RNS, RNK/E, RNK/XT) werden während des Einbaus oder Austauschs von Fenstern installiert und sitzen direkt auf dem Blendrahmen. Vorsatzrolläden (RAK/E, RAS, RAR/E) können im Nachhinein montiert werden und lassen sich in die Gebäudefassade integrieren.\n\nAlle Varianten sind in zahlreichen Farben erhältlich und auf Maß gefertigt.',
    specs: [
      { label: 'Aufsatz 1', value: 'RNS' },
      { label: 'Aufsatz 2', value: 'RNK/E' },
      { label: 'Aufsatz 3', value: 'RNK/XT' },
      { label: 'Vorsatz 1', value: 'RAK/E' },
      { label: 'Vorsatz 2', value: 'RAS' },
      { label: 'Vorsatz 3', value: 'RAR/E' },
      { label: 'Fertigung', value: 'Maßanfertigung' },
    ],
    features: [
      'Aufsatzrolläden RNS, RNK/E, RNK/XT – Montage beim Fenstereinbau',
      'Vorsatzrolläden RAK/E, RAS, RAR/E – nachträgliche Montage möglich',
      'In Gebäudefassade integrierbar',
      'Einbruchschutz, Sonnenschutz und Wärmedämmung',
      'Maßanfertigung nach Kundenwunsch',
      'Zahlreiche Farben verfügbar',
    ],
    badges: [
      { type: 'german-market', label: 'Geeignet für den deutschen Markt' },
    ],
  },

];
