const PRODUCTS = [

  // ── KUNSTSTOFF ──────────────────────────────────────────────────────────────

  {
    id: 'ideal-8000',
    name: 'IDEAL 8000',
    tagline: 'Das Passivhaus-Fenster',
    category: 'Kunststoff',
    badge: 'Bestseller',
    image: 'images/ideal-8000.png',
    imageContain: true,
    gallery: [
      'images/ideal-8000.png',
    ],
    shortDesc: 'Höchste Energieeffizienz für Neubauten und anspruchsvolle Sanierungen. Passivhaus-geeignet, RC2 Einbruchschutz, 6 Kammern, 3 Dichtungen.',
    description: 'Die ENERGIESPARENDEN Fenster im Fenstersystem IDEAL 8000 sind eine Kombination modernster technischer Lösungen, die Wärme, Ruhe und Sicherheit garantieren. Diese Fenster sind für Investoren konzipiert, die an sicherem, energieeffizientem und passivem Bauen interessiert sind.\n\nMit einem Uw-Wert von nur 0,76 W/m²K erfüllt das IDEAL 8000 alle Anforderungen des Passivhausstandards und bietet gleichzeitig zertifizierten Einbruchschutz der Klasse RC2. Durch die 6-Kammer-Konstruktion und 3 umlaufende Dichtungen erreicht das Profil eine Bautiefe von 85 mm – für optimale Wärmedämmung auch bei extremen Klimabedingungen.\n\nMit über 38 verfügbaren Dekorfolien lässt es sich individuell an jede Architektursprache anpassen. Ideal für Neubauten, Passivhäuser und hochwertige Sanierungen – wenn keine Kompromisse beim Energiestandard gemacht werden dürfen.',
    specs: [
      { label: 'Uw-Wert', value: '0,76* W/m²K' },
      { label: 'Bautiefe', value: '85 mm' },
      { label: 'Kammern', value: '6' },
      { label: 'Dichtungen', value: '3 umlaufend' },
      { label: 'Einbruchschutz', value: 'RC2' },
      { label: 'Standard', value: 'Passivhaus' },
      { label: 'Dekore', value: '38 Sorten' },
      { label: 'Verglasung', value: '3-fach' },
    ],
    specsNote: '* Der Uw-Wert betrifft das Referenzfenster mit dem Maß 1230×1480 mm, der 3-fach Verglasung mit warmer Kante und Ug-Wert 0,5 W/m²K.',
    features: [
      'Passivhaus-geeignet (zertifiziert)',
      'Einbruchschutz Klasse RC2',
      '6 Kammern, 3 umlaufende Dichtungen',
      'Bis zu 38 Dekorfolien verfügbar',
      'CE-zertifiziert',
      'Für Neubau und Sanierung geeignet',
    ],
    badges: [
      { type: 'german-market', label: 'Geeignet für den deutschen Markt' },
      { type: 'passivhaus', label: 'Passivhaus' },
      { type: 'rc2', label: 'RC2 Einbruchschutz' },
    ],
    variants: [
      { name: 'Classic Line', color: '#ffffff', border: '#d1d5db', profile: '180×05' },
      { name: 'Standard', color: '#7B4A2D', border: '#7B4A2D', profile: '180×05' },
      { name: 'Anthrazit', color: '#3C3C3C', border: '#3C3C3C', profile: '180×20' },
    ],
  },

  {
    id: 'ideal-7000',
    name: 'IDEAL 7000',
    tagline: 'Premium ENERGO-Fenster',
    category: 'Kunststoff',
    badge: 'Energie A+',
    image: 'images/produkt-2-ideal7000.png',
    gallery: [
      'images/produkt-2-ideal7000.png',
      'images/produkt-2-ideal7000-2.png',
    ],
    shortDesc: 'Premiumfenster ENERGO auf Basis des IDEAL 7000-Profils. RC2 Einbruchschutz, 6 Kammern, 85 mm Bautiefe – ideal für moderne Einfamilienhäuser.',
    description: 'Premiumfenster ENERGO, die auf Basis des IDEAL 7000-Profils hergestellt werden, sind ein Beispiel für die Kombination der Eigenschaften von Profil und Isolierglas, um Fenster mit sehr niedrigem Wärmedurchgangskoeffizienten zu schaffen. Vor allem in modernen Einfamilienhäusern ist dies eine hervorragende Wahl.\n\nMit einem Uw-Wert von 0,79 W/m²K, 6 Kammern und 85 mm Bautiefe bietet das IDEAL 7000 hervorragende Wärmedämmeigenschaften bei gleichzeitigem Einbruchschutz der Klasse RC2. Das 3-fach Glaspaket sorgt für optimale Schall- und Wärmedämmung.\n\nMit bis zu 38 Dekorfolien lässt sich das Profil individuell an jede Architektursprache anpassen – in Standardweiß oder mit anthrazitgrauem Kern.',
    specs: [
      { label: 'Uw-Wert', value: '0,79* W/m²K' },
      { label: 'Bautiefe', value: '85 mm' },
      { label: 'Kammern', value: '6' },
      { label: 'Dichtungen', value: '2 umlaufend' },
      { label: 'Einbruchschutz', value: 'RC2' },
      { label: 'Glaspaket', value: '3-fach' },
      { label: 'Dekore', value: '38 Sorten' },
      { label: 'Zertifizierung', value: 'CE' },
    ],
    specsNote: '* Der Uw-Wert betrifft das Referenzfenster mit dem Maß 1230×1480 mm und der 2-fach Verglasung mit warmer Kante und Ug-Wert 1,1 W/m²K.',
    features: [
      'Einbruchschutz Klasse RC2',
      '6 Kammern, 2 umlaufende Dichtungen',
      '85 mm Bautiefe',
      '3-fach Glaspaket',
      'Bis zu 38 Dekorfolien verfügbar',
      'CE-zertifiziert',
      'Ideal für moderne Einfamilienhäuser',
    ],
    badges: [
      { type: 'rc2', label: 'RC2 Einbruchschutz' },
      { type: 'ce', label: 'CE-zertifiziert' },
    ],
    variants: [
      { name: 'Standard', color: '#ffffff', border: '#d1d5db', profile: '170×02 / 170×20' },
      { name: 'Anthrazitgrauer Kern', color: '#3C3C3C', border: '#3C3C3C', profile: '170×02 / 170×20' },
    ],
  },

  {
    id: 'neo',
    name: 'NEO – New Look',
    tagline: 'Zeitlos kubisches Design',
    category: 'Kunststoff',
    badge: 'Design',
    image: 'images/produkt-3-neo.png',
    gallery: [
      'images/produkt-3-neo.png',
      'images/produkt-3-neo-2.png',
    ],
    shortDesc: 'Zeitloses kubisches Design mit symmetrischer Profilform. ift Rosenheim zertifiziert, 6 Kammern, 76 mm Bautiefe.',
    description: 'Die NEW LOOK Fenster sind ein äußerst attraktives Designangebot für Kunden, die Wert auf einen zeitlosen Stil legen. Die symmetrische, kubistische Form ist das charakteristische Merkmal der Fenster im NEO-System. Die NEW LOOK Fenster sind ein schlichtes und schönes Design für jedes Zuhause. Sie schaffen eine harmonische Verbindung zwischen Innen- und Außenelementen, wodurch der Raum heller und einladender wirkt.\n\nMit einem Uw-Wert von 0,78 W/m²K und einer Bautiefe von 76 mm bietet das NEO hervorragende Wärmedämmeigenschaften bei schmalem Profil. Das Profil ist mit 2- oder 3-fach Glaspaket sowie 2 oder 3 Dichtungen erhältlich und passt sich so optimal an unterschiedliche Anforderungen an.\n\nMit bis zu 38 Dekorfolien lässt sich das NEO individuell gestalten – ein schlichtes und schönes Design für jedes Zuhause.',
    specs: [
      { label: 'Uw-Wert', value: '0,78* W/m²K' },
      { label: 'Bautiefe', value: '76 mm' },
      { label: 'Kammern', value: '6' },
      { label: 'Dichtungen', value: '2 o. 3' },
      { label: 'Glaspaket', value: '2- o. 3-fach' },
      { label: 'Dekore', value: '38 Sorten' },
      { label: 'Zertifizierung', value: 'ift Rosenheim + CE' },
    ],
    specsNote: '* Der Uw-Wert betrifft das Referenzfenster NEO MD mit dem Maß 1230×1480 mm und der 2-fach Verglasung mit warmer Kante und Ug-Wert 1,0 W/m²K.',
    features: [
      'Symmetrisches, kubisches Profil',
      'Harmonische Verbindung Innen- und Außenbereich',
      '6 Kammern, 76 mm Bautiefe',
      '2- oder 3-fach Glaspaket wählbar',
      '2 oder 3 Dichtungen',
      'Bis zu 38 Dekorfolien',
      'ift Rosenheim zertifiziert',
      'CE-zertifiziert',
    ],
    badges: [
      { type: 'ift', label: 'ift Rosenheim zertifiziert' },
      { type: 'ce', label: 'CE-zertifiziert' },
    ],
    variants: [
      { name: 'NEO MD', color: '#ffffff', border: '#d1d5db', profile: '160×07 / 160×20' },
      { name: 'NEO AD', color: '#C4A882', border: '#C4A882', profile: '160×01 / 160×20' },
    ],
  },

  {
    id: 'ideal-4000',
    name: 'IDEAL 4000',
    tagline: 'Universal ECO-Fenster',
    category: 'Kunststoff',
    image: 'images/produkt-4-ideal4000.png',
    gallery: [
      'images/produkt-4-ideal4000.png',
      'images/produkt-4-ideal4000-2.png',
    ],
    shortDesc: 'UNIVERSAL ECO-Fenster in klassischer und runder Profillinie. Perfekte Balance aus Ökonomie und Ökologie – ift Rosenheim zertifiziert.',
    description: 'UNIVERSAL ECO-Fenster, basierend auf dem IDEAL 4000 Profil, bieten die perfekte Balance zwischen klassischem Design und den funktionalen Aspekten modernster Bautechnologien. Die UNIVERSAL ECO-Fenster, die in zwei Profiltypen (klassisch und rund) sowie in Drei- und Doppelglaspaketen angeboten werden, gewährleisten die optimale Kombination von Ökonomie und Ökologie.\n\nMit 5 Kammern, 2 Dichtungen und einer Bautiefe von 70 mm ist das IDEAL 4000 eine solide und langlebige Wahl für Wohngebäude, Mehrfamilienhäuser und Sanierungsprojekte. Die ift Rosenheim-Zertifizierung belegt die geprüfte Qualität nach europäischem Standard.\n\nMit bis zu 38 Dekorfolien lässt es sich individuell gestalten.',
    specs: [
      { label: 'Uw-Wert', value: '1,28* W/m²K' },
      { label: 'Bautiefe', value: '70 mm' },
      { label: 'Kammern', value: '5' },
      { label: 'Dichtungen', value: '2 umlaufend' },
      { label: 'Glaspaket', value: '2- o. 3-fach' },
      { label: 'Dekore', value: '38 Sorten' },
      { label: 'Zertifizierung', value: 'ift Rosenheim + CE' },
    ],
    specsNote: '* Der Uw-Wert betrifft das Referenzfenster mit dem Maß 1230×1480 mm und der 2-fach Verglasung mit warmer Kante und Ug-Wert 1,1 W/m²K.',
    features: [
      '5 Kammern, 70 mm Bautiefe',
      '2 umlaufende Dichtungen',
      '2- oder 3-fach Glaspaket wählbar',
      'Classic Line und Round-Line verfügbar',
      'Bis zu 38 Dekorfolien',
      'ift Rosenheim zertifiziert',
      'CE-zertifiziert',
    ],
    badges: [
      { type: 'ift', label: 'ift Rosenheim zertifiziert' },
      { type: 'ce', label: 'CE-zertifiziert' },
    ],
    variants: [
      { name: 'Classic Line', color: '#ffffff', border: '#d1d5db', profile: '140×01 / 140×20' },
      { name: 'Round-Line', color: '#f3f4f6', border: '#d1d5db', profile: '140×01 / 140×22' },
    ],
  },

  {
    id: 'ideal-5000',
    name: 'IDEAL 5000',
    tagline: 'Das vielseitige Mittelklasse-Fenster',
    category: 'Kunststoff',
    badge: 'Beliebt',
    image: 'images/produkt-5-ideal5000.png',
    gallery: [
      'images/produkt-5-ideal5000.png',
      'images/produkt-5-ideal5000-2.png',
    ],
    shortDesc: 'Die ausgezeichneten Dämmeigenschaften des IDEAL 5000 garantieren erstklassigen Wohnkomfort. ift Rosenheim zertifiziert, 5 Kammern, 70 mm Bautiefe.',
    description: 'Die ausgezeichneten Dämmeigenschaften des IDEAL 5000 garantieren erstklassigen Wohnkomfort. Die hochwertigen Profilsysteme von ALUPLAST gewährleisten zudem hervorragenden Einbruchschutz und somit ein beruhigendes Maß an Sicherheit.\n\nMit 5 Kammern, 3 umlaufenden Dichtungen und einer Bautiefe von 70 mm bietet das IDEAL 5000 eine solide und bewährte Lösung für Wohngebäude, Mehrfamilienhäuser und Sanierungsprojekte. Das 2- oder 3-fach Glaspaket ist frei wählbar.\n\nDas Profil ist in 5 hochwertigen Folienvarianten erhältlich – von klassisch Weiß über Golden Eiche bis hin zu modernem Jetblack Tiefschwarz.',
    specs: [
      { label: 'Uw-Wert', value: '1,23* W/m²K' },
      { label: 'Bautiefe', value: '70 mm' },
      { label: 'Kammern', value: '5' },
      { label: 'Dichtungen', value: '3 umlaufend' },
      { label: 'Glaspaket', value: '2- o. 3-fach' },
      { label: 'Dekore', value: '5 Sorten' },
      { label: 'Zertifizierung', value: 'ift Rosenheim + CE' },
    ],
    specsNote: '* Wärmedämmungskoeffizient eines Fensters Referenzabmessungen 1230×1480 mm, unter Verwendung einer Glasscheibe mit einem heißen Rahmen mit dem Koeffizienten Ug=1,1 W/m²K 4/16/4.',
    features: [
      '5 Kammern, 70 mm Bautiefe',
      '3 umlaufende Dichtungen',
      '2- oder 3-fach Glaspaket wählbar',
      '5 Foliensorten: Weiß, Golden Eiche, Anthrazit, Sandgrau, Jetblack',
      'ift Rosenheim zertifiziert',
      'CE-zertifiziert',
    ],
    badges: [
      { type: 'ift', label: 'ift Rosenheim zertifiziert' },
      { type: 'ce', label: 'CE-zertifiziert' },
    ],
    variants: [
      { name: 'Weiss Glatt', color: '#ffffff', border: '#d1d5db', profile: '150×02 / 150×20' },
      { name: 'Golden Eiche', color: '#8B5E2A', border: '#8B5E2A', profile: '150×02 / 150×20' },
      { name: 'Anthrazit Sandgrau', color: '#6B7280', border: '#6B7280', profile: '150×02 / 150×20' },
      { name: 'Sandgrauer Quarz', color: '#9CA3AF', border: '#9CA3AF', profile: '150×02 / 150×20' },
      { name: 'Jetblack Tiefschwarz', color: '#111827', border: '#111827', profile: '150×02 / 150×20' },
    ],
  },

  // ── HEBE-SCHIEBE ────────────────────────────────────────────────────────────

  {
    id: 'hst',
    name: 'HST Hebeschiebetür',
    tagline: 'Panoramablick ohne Kompromisse',
    category: 'Hebe-Schiebe',
    badge: 'Passivhaus',
    image: 'images/produkt-6-hst.png',
    gallery: [
      'images/produkt-6-hst.png',
      'images/produkt-6-hst-2.png',
    ],
    shortDesc: 'Die HST Hebeschiebetür bietet komfortable Verbindung zwischen Innen und Terrasse. Passivhaus-geeignet, Breiten bis 6,50 m, flache Schwelle.',
    description: 'Die Verwendung von HST-Hebeschiebetüren bietet eine ideale Lösung für alle, die eine komfortable Verbindung zwischen Innenraum und Terrasse wünschen und gleichzeitig von einem Panoramablick durch großzügige Glasflächen profitieren möchten. HST-Terrassentüren zeichnen sich durch ihre großzügigen Abmessungen aus, die die Herstellung von Verglasungen mit einer Breite von bis zu sechseinhalb Metern ermöglichen.\n\nDieses System ermöglicht die Konstruktion von Türen in erweiterten Abmessungen. Innerhalb dieses Systems kann die Breite dieser Türen beeindruckende 6,5 Meter erreichen. Dank spezieller Mechanismen lassen sich diese mühelos verschieben. HST-Türen sind zudem mit einer flachen Schwelle ausgestattet, und auf Wunsch des Kunden kann eine spezielle Bremse hinzugefügt werden.',
    specs: [
      { label: 'Uw-Wert', value: '0,71* W/m²K' },
      { label: 'Tauglich', value: 'Passivhaus' },
      { label: 'Bautiefe', value: '70 mm' },
      { label: 'Rahmentiefe', value: '85 mm' },
      { label: 'Max. Höhe', value: '2.700 mm' },
      { label: 'Max. Breite', value: '6.500 mm' },
      { label: 'Dekore', value: '38 Sorten' },
      { label: 'Zertifizierung', value: 'CE' },
    ],
    specsNote: '* Der Uw-Wert für eine Hebe-Schiebe-Tür HST Premium mit den Maßen 4000×2300 mm und einer Verglasung mit einem Ug-Wert von 0,5 W/m²K beträgt 0,71 W/m²K.',
    features: [
      'Passivhaus-geeignet',
      'Breiten bis 6.500 mm, Höhen bis 2.700 mm',
      'Bautiefe 70 mm, Rahmentiefe 85 mm',
      'Flache barrierefreie Schwelle',
      'Mühelos verschiebbar dank spezieller Mechanismen',
      'Optionale Bremse auf Kundenwunsch',
      '38 Dekorfolien',
      'CE-zertifiziert',
    ],
    badges: [
      { type: 'passivhaus', label: 'Passivhaus' },
      { type: 'ce', label: 'CE-zertifiziert' },
    ],
    variants: [
      { name: 'HST Premium', color: '#ffffff', border: '#d1d5db', profile: '' },
      { name: 'HST Basic', color: '#f3f4f6', border: '#d1d5db', profile: '' },
      { name: 'HST 85 Fixframe', color: '#e5e7eb', border: '#d1d5db', profile: '' },
    ],
  },

  {
    id: 'psk',
    name: 'PSK Smart Slide Neo',
    tagline: 'Parallel-Schiebe-Kipp auf neuem Level',
    category: 'Hebe-Schiebe',
    badge: 'Neuheit',
    image: 'images/produkt-7-psk.png',
    gallery: [
      'images/produkt-7-psk.png',
      'images/produkt-7-psk-2.png',
      'images/produkt-7-psk-3.png',
      'images/produkt-7-psk-4.png',
    ],
    shortDesc: 'Terrassentüren im Schiebesystem für großflächige Verglasungen bei voller Wärmedämmung. Leichte Bedienung unabhängig von Größe und Gewicht.',
    description: 'Terrassentüren im Schiebesystem ermöglichen die Schaffung großflächiger Verglasungen, wobei gleichzeitig die volle Wärmedämmung erhalten bleibt. Unabhängig von ihrer Größe und ihrem Gewicht arbeiten die Terrassentüren im Schiebe- und Kipp-Schiebe-System effizient und sind leicht zu bedienen.\n\nDer Smart Slide Neo benötigt wenig Raum und ermöglicht die Schaffung einer breiten Durchgangsöffnung zur Terrasse. Wenn die Tür geschlossen ist, bilden der Schiebeflügel und der Festflügel eine ästhetische Linie. Die Tür verfügt über eine moderne und breite Schwelle, die vielfältige Anwendungsmöglichkeiten bietet, auch im Bereich der Renovierung.\n\nDie Variante PATIO eignet sich mit ihrer traditionellen Schwelle ideal für klassische Balkontüren.',
    specs: [
      { label: 'Bautiefe (Neo)', value: '78 mm' },
      { label: 'Rahmentiefe (Neo)', value: '154 mm' },
      { label: 'Max. Höhe (Neo)', value: '6.000 mm' },
      { label: 'Max. Breite (Neo)', value: '2.500 mm' },
      { label: 'Bautiefe (Patio)', value: '85 mm' },
      { label: 'Max. Höhe (Patio)', value: '2.300 mm' },
      { label: 'Max. Breite (Patio)', value: '1.400 mm' },
    ],
    features: [
      'Parallel-Schiebe-Kipp-Funktion',
      'Smart Slide Neo: max. 6.000 mm Höhe, 2.500 mm Breite',
      'Moderne breite Schwelle (Neo) – ideal für Renovierung',
      'Patio: klassische Schwelle für Balkontüren',
      'Schiebeflügel und Festflügel bilden ästhetische Linie',
      'Leichte Bedienung unabhängig von Größe und Gewicht',
    ],
    badges: [
      { type: 'ce', label: 'CE-zertifiziert' },
    ],
    variants: [
      { name: 'Smart Slide Neo', color: '#ffffff', border: '#d1d5db', profile: '78 mm / 154 mm Rahmen', image: 'images/produkt-7-psk.png' },
      { name: 'Patio', color: '#3C3C3C', border: '#3C3C3C', profile: '85 mm Bautiefe', image: 'images/produkt-7-psk-2.png' },
    ],
  },

  // ── HAUSTÜREN ────────────────────────────────────────────────────────────────

  {
    id: 'eingangstuer-pvc',
    name: 'Eingangstür PVC',
    tagline: 'Sicherheit, Langlebigkeit und Eleganz',
    category: 'Haustür',
    badge: 'Beliebt',
    image: 'images/produkt-8-eingangstuer-pvc.png',
    imageContain: true,
    gallery: [
      'images/produkt-8-eingangstuer-pvc.png',
    ],
    shortDesc: 'Die Haustür ist das Aushängeschild des Hauses. PVC-Profile in Premium (85 mm) und Basic (70 mm), vielfältige Paneele, verstärkte Beschläge.',
    description: 'Die Haustür ist das Aushängeschild des Hauses. Bei der Auswahl von PVC-Türen können Sie sich auf Sicherheit, Langlebigkeit und Eleganz verlassen. Starke und robuste PVC-Profile bilden die Grundlage für eine breite Palette von Paneelen, sowohl modern als auch traditionell. Verstärkte Beschläge gewährleisten langanhaltenden Nutzungskomfort.\n\nDas Profil ist in zwei Ausführungen erhältlich: PREMIUM IDEAL 7000 mit 85 mm Bautiefe für höchste Ansprüche, sowie BASIC IDEAL 4000 mit 70 mm Bautiefe als solide Einstiegslösung.\n\nDrei Füllungsvarianten stehen zur Auswahl: Beidseitige Aufsatzfüllung, Einseitige Aufsatzfüllung und Standard Einsatzfüllung – für jede Gestaltungsanforderung die passende Lösung.',
    specs: [
      { label: 'Profil Premium', value: 'IDEAL 7000 – 85 mm' },
      { label: 'Profil Basic', value: 'IDEAL 4000 – 70 mm' },
      { label: 'Füllung', value: '3 Varianten' },
      { label: 'Beschläge', value: 'Verstärkt' },
      { label: 'Material', value: 'PVC' },
    ],
    features: [
      'Premium IDEAL 7000 Profil (85 mm)',
      'Basic IDEAL 4000 Profil (70 mm)',
      'Beidseitige Aufsatzfüllung',
      'Einseitige Aufsatzfüllung',
      'Standard Einsatzfüllung',
      'Verstärkte Beschläge',
      'Modern und traditionell verfügbar',
    ],
    badges: [
      { type: 'ce', label: 'CE-zertifiziert' },
    ],
    variants: [
      { name: 'Premium IDEAL 7000', color: '#ffffff', border: '#d1d5db', profile: '85 mm' },
      { name: 'Basic IDEAL 4000', color: '#f3f4f6', border: '#d1d5db', profile: '70 mm' },
    ],
  },

  {
    id: 'alu-schiebe',
    name: 'Ziehgriffe',
    tagline: 'Design-Türgriffe für Haustüren & Eingänge',
    category: 'Zubehör',
    badge: 'Neuheit',
    image: 'images/ziehgriffe.png',
    imageContain: true,
    gallery: ['images/ziehgriffe.png'],
    shortDesc: 'Hochwertige Ziehgriffe in verschiedenen Designs – von schlicht bis architektonisch, für Haustüren, Eingänge und Schiebetüren.',
    description: 'Unsere Ziehgriffe verbinden Funktion mit Design und setzen an jeder Tür einen markanten Akzent. Das Sortiment umfasst zwölf Modelle in unterschiedlichen Formen und Oberflächen – von schlanken Rundprofilen bis zu eckigen Designgriffen.\n\nVerfügbare Modelle: Z2 B30, Z6 B30, Z8, Z2 40, Z2 30, Z2 K30, Z2 B40, Z6 BB30, Z27 40X20, Z32, Z43, Z6 W30.\n\nAlle Griffe sind aus hochwertigem Stahl gefertigt und in verschiedenen Oberflächen erhältlich – Schwarz matt, Edelstahl gebürstet und Weiß. Passend für alle gängigen Haustür- und Eingangstürsysteme.',
    specs: [
      { label: 'Material', value: 'Stahl / Edelstahl' },
      { label: 'Oberflächen', value: 'Schwarz, Edelstahl, Weiß' },
      { label: 'Modelle', value: '12 Varianten' },
      { label: 'Passend für', value: 'Haustüren, Eingänge' },
    ],
    features: [
      '12 verschiedene Griffmodelle',
      'Oberflächen: Schwarz matt, Edelstahl, Weiß',
      'Passend für alle gängigen Türsysteme',
      'Schlichte und architektonische Designs',
      'Auf Anfrage auch Sondermaße',
    ],
  },

  // ── ALUMINIUM ────────────────────────────────────────────────────────────────

  {
    id: 'alu-thermo',
    name: 'Türgriffe & Türzubehör',
    tagline: 'Komplettes Zubehörsortiment für Türen',
    category: 'Zubehör',
    badge: 'Komplettsortiment',
    image: 'images/tuergriffe-zubehoer.png',
    imageContain: true,
    gallery: ['images/tuergriffe-zubehoer.png'],
    shortDesc: 'Türgriffe, Fingerabdruckleser, Bluetooth-Tastatur, Aluminium- und Automatikschwell – alles aus einer Hand.',
    description: 'Unser Türzubehör-Sortiment bietet alles, was eine hochwertige Tür komplett macht – von klassischen Türgriffen bis zu modernen Smart-Access-Lösungen.\n\nTürgriffe: Modelle P01, P10, P04 und TG12 in verschiedenen Ausführungen – passend für alle gängigen Haustür- und Eingangstürsysteme.\n\nZutrittssysteme: Fingerabdruckleser für berührungslosen Zugang sowie Tastatur mit Code und Bluetooth für flexible Zugangskontrolle.\n\nSchwellen: Aluminiumschwelle für dauerhaften wetterfesten Abschluss sowie Automatische Schwelle für barrierefreien und zugluftfreien Eingang.',
    specs: [
      { label: 'Griffmodelle', value: 'P01, P10, P04, TG12' },
      { label: 'Zugang', value: 'Fingerprint / Bluetooth' },
      { label: 'Schwellen', value: 'Alu / Automatik' },
      { label: 'Material', value: 'Edelstahl / Aluminium' },
    ],
    features: [
      'Türgriffe P01, P10, P04, TG12',
      'Fingerabdruckleser',
      'Tastatur mit Code & Bluetooth',
      'Aluminiumschwelle',
      'Automatische Schwelle (barrierefrei)',
    ],
  },

  {
    id: 'alu-ferroline',
    name: 'Klassische Kunststofftüren',
    tagline: 'Zeitlose Haustüren in klassischer Optik',
    category: 'Haustür',
    badge: 'Klassik',
    image: 'images/klassische-kunststofftueren.png',
    imageContain: true,
    gallery: ['images/klassische-kunststofftueren.png'],
    shortDesc: 'Klassische PVC-Haustüren mit und ohne Seitenteil – in zahlreichen Designs wie Sage, Model, Bekopa, Bartonia und mehr.',
    description: 'Unsere klassischen Kunststofftüren verbinden traditionelle Eleganz mit moderner PVC-Technologie. Das umfangreiche Sortiment umfasst Modelle mit und ohne Seitenteil – für jeden Geschmack und jede Fassade.\n\nModelle ohne Seitenteil: Sage 1, Model, Bekopa, Bartonia HB, Estragon, Iris, Boronia, Calendula.\n\nModelle mit Seitenteil: Safran, Sage, Bekopa, Nandina.\n\nAlle Modelle sind in verschiedenen Dekoren erhältlich – von klassischem Holzdekor bis zu modernem Weiß. ',
    specs: [
      { label: 'Material', value: 'PVC / Kunststoff' },
      { label: 'Varianten', value: 'Mit / ohne Seitenteil' },
      { label: 'Modelle', value: '12 Designs' },
      { label: 'Dekore', value: 'Holz, Weiß u.v.m.' },
    ],
    features: [
      '8 Modelle ohne Seitenteil',
      '4 Modelle mit Seitenteil',
      'Holzdekore und Weiß verfügbar',
      'Klassische und moderne Designs',
      'Passend für jeden Fassadentyp',
    ],
  },

  {
    id: 'alu-harmonika',
    name: 'Moderne Kunststofftüren',
    tagline: 'Zeitgemäße Haustüren in modernem Design',
    category: 'Haustür',
    badge: 'Modern',
    image: 'images/moderne-kunststofftueren.png',
    imageContain: true,
    gallery: ['images/moderne-kunststofftueren.png'],
    shortDesc: 'Moderne PVC-Haustüren in drei Ausführungen – ohne Seitenteil, mit Seitenteil und mit doppeltem Seiten- und Oberlicht.',
    description: 'Unsere modernen Kunststofftüren setzen klare Akzente und passen perfekt zu zeitgemäßer Architektur. Das Sortiment gliedert sich in drei Konfigurationen.\n\nOhne Seitenteil: 6172-83, 6233-09, 6172-94, 6184-54 – sachliche Designs mit modernen Glasausschnitten.\n\nMit Seitenteil: Alum, Carex, Gloriosa, Irge – für breitere Eingangssituationen mit elegantem Rahmen.\n\nMit doppeltem Seiten- und Oberlicht: Dahla, Ligustr – maximale Lichtöffnung für repräsentative Eingänge.\n\nAlle Modelle sind in verschiedenen Dekoren erhältlich.',
    specs: [
      { label: 'Material', value: 'PVC / Kunststoff' },
      { label: 'Varianten', value: 'Ohne / Mit Seitenteil' },
      { label: 'Modelle', value: '10 Designs' },
      { label: 'Oberlicht', value: 'Optional verfügbar' },
    ],
    features: [
      '4 Modelle ohne Seitenteil',
      '4 Modelle mit Seitenteil',
      '2 Modelle mit Seiten- & Oberlicht',
      'Moderne Glasausschnitte',
      'Verschiedene Dekore erhältlich',
    ],
  },

  // ── HAUSTÜREN ────────────────────────────────────────────────────────────────

  {
    id: 'haustuer-pvc',
    name: 'Thermo Aluminiumfenster',
    tagline: 'Aluminium-Qualität mit höchster Wärmedämmung',
    category: 'Aluminium',
    badge: 'Passivhaus',
    image: 'images/thermo-aluminiumfenster.png',
    imageContain: true,
    shortDesc: 'Thermo Aluminiumfenster in 4 Systemvarianten – vom Passivhausstandard bis zur klassischen Wärmedämmung. Profile von ALUPROF und ALUPLAST.',
    description: 'Unsere Thermo Aluminiumfenster bieten für jeden Anspruch das passende Profil – von höchster Wärmedämmung bis zur klassischen Variante. Alle Profile sind in beliebigen RAL-Farben lieferbar und lassen sich individuell auf Ihr Bauprojekt abstimmen.\n\nDas ALUPROF MB 104 PASSIVE erreicht Passivhausstandard und setzt Maßstäbe in der Energieeffizienz. Das ALUPLAST GENESIS 90 bietet hervorragende Wärmedämmung auf modernstem Niveau. Der ALUPROF MB 86 N ist ideal für anspruchsvolle Sanierungen und Neubauten. Der ALUPROF MB 45 rundet das Sortiment als klassische Aluminium-Variante ab.\n\nAlle Systeme sind für den deutschen Markt zugelassen und CE-zertifiziert.',
    specs: [
      { label: 'System 1', value: 'ALUPROF MB 104 PASSIVE' },
      { label: 'System 2', value: 'ALUPLAST GENESIS 90' },
      { label: 'System 3', value: 'ALUPROF MB 86 N' },
      { label: 'System 4', value: 'ALUPROF MB 45' },
      { label: 'Material', value: 'Aluminium' },
      { label: 'Standard', value: 'Passivhaus (MB 104)' },
      { label: 'Farben', value: 'Alle RAL-Farben' },
      { label: 'Zulassung', value: 'CE-zertifiziert' },
    ],
    features: [
      'ALUPROF MB 104 PASSIVE – höchste Wärmedämmung, Passivhausstandard',
      'ALUPLAST GENESIS 90 – hohe Wärmedämmung',
      'ALUPROF MB 86 N – solide Wärmedämmung für Neubau & Sanierung',
      'ALUPROF MB 45 – klassische Aluminium-Variante',
      'Alle RAL-Farben verfügbar',
      'CE-zertifiziert, für deutschen Markt zugelassen',
    ],
    badges: [
      { type: 'german-market', label: 'Geeignet für den deutschen Markt' },
      { type: 'passivhaus', label: 'Passivhaus' },
    ],
  },

  {
    id: 'haustuer-genesis',
    name: 'New Design Aluminiumfenster',
    tagline: 'Architektonisch anspruchsvolle Aluminium-Lösungen',
    category: 'Aluminium',
    badge: 'Design',
    image: 'images/new-design-aluminiumfenster.png',
    imageContain: true,
    shortDesc: 'New Design Aluminiumfenster in 4 Systemvarianten – Loft, Mehr-Licht, Industrie und Balustrade. Profile von ALUPROF und ALUPLAST.',
    description: 'NEW DESIGN Aluminiumfenster sind eine Lösung, die eine Reihe spezieller Anforderungen erfüllt. Je nach Profil meistern sie erfolgreich Loft- oder Industrieinstallationsräumen. Sie können auch eine maximale Belichtung von Räumen bei gleichzeitig sehr guten technischen Strukturparametern gewährleisten.\n\nDas ALUPROF MB FERROLINE überzeugt mit seinem Loft-Fenster-Charakter und industrieller Ästhetik. Der ALUPROF MB 79 N US maximiert den Lichteinfall als "Mehr Licht"-Fenster. Das ALUPLAST MAX LIGHT DESIGN ist die ideale Wahl für Industriefenster. Der ALUPROF GLASS BARRIER schließt das Sortiment als innovatives Fenster mit integrierter Balustrade ab.\n\nAlle Profile sind CE-zertifiziert und in beliebigen RAL-Farben verfügbar.',
    specs: [
      { label: 'System 1', value: 'ALUPROF MB FERROLINE' },
      { label: 'System 2', value: 'ALUPROF MB 79 N US' },
      { label: 'System 3', value: 'ALUPLAST MAX LIGHT DESIGN' },
      { label: 'System 4', value: 'ALUPROF GLASS BARRIER' },
      { label: 'Material', value: 'Aluminium' },
      { label: 'Farben', value: 'Alle RAL-Farben' },
      { label: 'Zulassung', value: 'CE-zertifiziert' },
    ],
    features: [
      'ALUPROF MB FERROLINE – Loft-Fenster mit industriellem Charakter',
      'ALUPROF MB 79 N US – maximaler Lichteinfall',
      'ALUPLAST MAX LIGHT DESIGN – Industriefenster',
      'ALUPROF GLASS BARRIER – Fenster mit integrierter Balustrade',
      'Alle RAL-Farben verfügbar',
      'CE-zertifiziert, für deutschen Markt zugelassen',
    ],
    badges: [
      { type: 'german-market', label: 'Geeignet für den deutschen Markt' },
    ],
  },

  {
    id: 'alu-untypisch',
    name: 'Untypische Aluminiumfenster',
    tagline: 'Spezialanwendungen für Innen und Außen',
    category: 'Aluminium',
    badge: 'Speziallösung',
    image: 'images/untypische-aluminiumfenster.png',
    imageContain: true,
    shortDesc: 'Basierend auf ALUPROF-Systemen: 4 Speziallösungen für Lüftung, Drehfenster, Schieben und Rauchabzug – horizontal und vertikal verschiebbar.',
    description: 'Basierend auf ALUPROF-Systemen bieten wir eine breite Palette von Fenstern für spezielle Anwendungen im Innen- und Außenbereich von Gebäuden. Sie können horizontal und vertikal verschoben werden und verfügen über eine vertikale oder horizontale Drehachse. Diese Fenster zeichnen sich durch Ästhetik, Langlebigkeit und Funktionalität aus.\n\nDas ALUPROF SLIDER WINDOW ist als Lüfterfenster ideal für kontrollierte Belüftung. Der ALUPROF PIVOT überzeugt als elegantes Drehfenster mit zentraler Drehachse. Das ALUPROF MB SLIDE ST bietet als Schiebefenster maximale Raumnutzung. Das ALUPROF Rauchabzugsfenster sorgt für zuverlässigen Rauchabzug mit integriertem Dämpfer – ideal für gewerbliche und öffentliche Gebäude.\n\nAlle Systeme sind CE-zertifiziert und in beliebigen RAL-Farben verfügbar.',
    specs: [
      { label: 'System 1', value: 'ALUPROF SLIDER WINDOW' },
      { label: 'System 2', value: 'ALUPROF PIVOT' },
      { label: 'System 3', value: 'ALUPROF MB SLIDE ST' },
      { label: 'System 4', value: 'ALUPROF Rauchabzug' },
      { label: 'Material', value: 'Aluminium' },
      { label: 'Farben', value: 'Alle RAL-Farben' },
      { label: 'Zulassung', value: 'CE-zertifiziert' },
    ],
    features: [
      'ALUPROF SLIDER WINDOW – Lüfterfenster, horizontal verschiebbar',
      'ALUPROF PIVOT – Drehfenster mit zentraler Achse',
      'ALUPROF MB SLIDE ST – Schiebefenster für maximale Raumnutzung',
      'ALUPROF Rauchabzugsfenster mit Dämpfer',
      'Alle RAL-Farben verfügbar',
      'CE-zertifiziert, für deutschen Markt zugelassen',
    ],
    badges: [
      { type: 'german-market', label: 'Geeignet für den deutschen Markt' },
    ],
  },

  {
    id: 'alu-schiebetueren',
    name: 'Aluminium Schiebetüren',
    tagline: 'Große Flächen, fließende Übergänge',
    category: 'Aluminium',
    badge: 'Großformat',
    image: 'images/aluminium-schiebetueren.png',
    imageContain: true,
    shortDesc: 'Aluminium-Schiebetürsysteme in 4 Varianten – HST, SlideGalandage, Slide System und Multi Slide. Für großflächige Verglasungen und architektonisch anspruchsvolle Lösungen.',
    description: 'Aluminium-Schiebetürsysteme erlauben das Öffnen der Tür in ihrer vollen Höhe ohne einschränkende Systeme. Diese raumeinnehmenden Systeme ermöglichen die Gestaltung von Wintergärten und großflächigen Verglasungen. Je nach architektonischem Design können mehrere Flügel eingebaut werden, die sogar in der Wand versteckt werden können.\n\nDer ALUPROF MB-59HS ist ein HST-System mit niedriger Schwelle für barrierefreies Wohnen. Die ALUPROF MB-59 SlideGalandage verschwindet komplett in der Wand. Der ALUPROF MB-77HS HI bietet als Slide System höchste Wärmedämmung. Das ALUPROF MB-SLIDE als Multi Slide System ermöglicht mehrteilige Panoramaverglasung.\n\nAlle Systeme sind CE-zertifiziert und in beliebigen RAL-Farben verfügbar.',
    specs: [
      { label: 'System 1', value: 'ALUPROF MB-59HS' },
      { label: 'System 2', value: 'ALUPROF MB-59 SlideGalandage' },
      { label: 'System 3', value: 'ALUPROF MB-77HS HI' },
      { label: 'System 4', value: 'ALUPROF MB-SLIDE' },
      { label: 'Material', value: 'Aluminium' },
      { label: 'Farben', value: 'Alle RAL-Farben' },
      { label: 'Zulassung', value: 'CE-zertifiziert' },
    ],
    features: [
      'ALUPROF MB-59HS – HST-System mit niedriger Schwelle',
      'ALUPROF MB-59 SlideGalandage – in der Wand versteckbar',
      'ALUPROF MB-77HS HI – Slide System mit hoher Wärmedämmung',
      'ALUPROF MB-SLIDE – Multi Slide System für Panoramaverglasung',
      'Alle RAL-Farben verfügbar',
      'CE-zertifiziert, für deutschen Markt zugelassen',
    ],
    badges: [
      { type: 'german-market', label: 'Geeignet für den deutschen Markt' },
    ],
  },

  {
    id: 'alu-falltueren',
    name: 'Aluminium Falttüren',
    tagline: 'Harmonika-Lösung für Terrasse & Wintergarten',
    category: 'Aluminium',
    badge: 'Harmonika',
    image: 'images/aluminium-falltueren.png',
    imageContain: true,
    shortDesc: 'Falttüren aus Aluminium (Harmonika-Form) für Terrassen und Wintergärten. Großflächige Verglasung bei minimalem Platzbedarf im geöffneten Zustand.',
    description: 'Falttüren aus Aluminium, auch als Harmonika-Form bezeichnet, finden hauptsächlich Verwendung als Eingänge zu Terrassen oder Wintergärten. Diese technische Lösung ermöglicht die Schaffung großflächiger Verglasungen bei gleichzeitig minimalem Platzbedarf im geöffneten Zustand.\n\nHarmonikalösungen eignen sich perfekt, um den Wohnraum auch im Winter nahtlos mit einer Terrasse oder einem Garten zu verbinden. Die Falttüren bestehen aus wärmegedämmten Profilen. Je nach Bedarf können sie nach innen oder nach außen öffnende Strukturen aufweisen.\n\nCE-zertifiziert, RAL-Gütezeichen, in allen RAL-Farben verfügbar.',
    specs: [
      { label: 'Typ', value: 'Harmonika / Falttür' },
      { label: 'Material', value: 'Aluminium' },
      { label: 'Profil', value: 'Wärmegedämmt' },
      { label: 'Öffnung', value: 'Nach innen oder außen' },
      { label: 'Verglasung', value: 'Großflächig' },
      { label: 'Farben', value: 'Alle RAL-Farben' },
      { label: 'Zulassung', value: 'CE-zertifiziert' },
    ],
    features: [
      'Harmonika-Falttür für Terrassen und Wintergärten',
      'Wärmegedämmte Aluminiumprofile',
      'Öffnung nach innen oder außen möglich',
      'Minimaler Platzbedarf im geöffneten Zustand',
      'Großflächige Verglasung',
      'Alle RAL-Farben verfügbar',
      'CE-zertifiziert, RAL-Gütezeichen',
    ],
    badges: [
      { type: 'german-market', label: 'Geeignet für den deutschen Markt' },
    ],
  },

  {
    id: 'alu-eingangstueren',
    name: 'Aluminium Eingangstüren',
    tagline: 'Hohe Steifigkeit und Festigkeit bei geringem Gewicht',
    category: 'Haustür',
    badge: 'RC2',
    image: 'images/aluminium-eingangstueren.png',
    imageContain: true,
    shortDesc: 'Aluminium-Eingangstüren in 4 Systemen – Genesis 75, Imperial 800, MB 104 Passive und MB-86. Hohe Steifigkeit, geringe Dichte, sicherheitsrelevant.',
    description: 'Der Hauptvorteil von Aluminium-Türen ist die hohe Steifigkeit und Festigkeit bei gleichzeitig geringem Gewicht. Sie verhalten sich während des Gebrauchs nicht. Festigkeitsparameter sind auch für die Einbruchsicherung von Bedeutung und werden daher häufig von sicherheitsbewussten Anlegern gewählt.\n\nALUPLAST GENESIS 75 kombiniert elegantes Design mit robuster Konstruktion. Das ALUPLAST IMPERIAL 800 bietet maximale Repräsentanz für anspruchsvolle Eingangsbereiche. Der ALUPROF MB 104 PASSIVE erreicht Passivhausstandard auch bei Türen. Der ALUPROF MB-86 rundet das Sortiment als solide Standardlösung ab.\n\nAlle Systeme sind CE-zertifiziert und in beliebigen RAL-Farben verfügbar.',
    specs: [
      { label: 'System 1', value: 'ALUPLAST GENESIS 75' },
      { label: 'System 2', value: 'ALUPLAST IMPERIAL 800' },
      { label: 'System 3', value: 'ALUPROF MB 104 PASSIVE' },
      { label: 'System 4', value: 'ALUPROF MB-86' },
      { label: 'Material', value: 'Aluminium' },
      { label: 'Farben', value: 'Alle RAL-Farben' },
      { label: 'Zulassung', value: 'CE-zertifiziert' },
    ],
    features: [
      'ALUPLAST GENESIS 75 – elegante Aluminium-Eingangstür',
      'ALUPLAST IMPERIAL 800 – repräsentativer Eingang',
      'ALUPROF MB 104 PASSIVE – Passivhausstandard auch für Türen',
      'ALUPROF MB-86 – solide Standardlösung mit hoher Steifigkeit',
      'Alle RAL-Farben verfügbar',
      'CE-zertifiziert, für deutschen Markt zugelassen',
    ],
    badges: [
      { type: 'german-market', label: 'Geeignet für den deutschen Markt' },
      { type: 'passivhaus', label: 'Passivhaus (MB 104)' },
    ],
  },

  {
    id: 'aussenrollaeden',
    name: 'Außenrolläden',
    tagline: 'Sonnenschutz, Sichtschutz & Wärmedämmung',
    category: 'Zubehör',
    badge: 'Sonnenschutz',
    image: 'images/aussenrollaeden.png',
    imageContain: true,
    shortDesc: 'Außenrolläden als wichtige architektonische Elemente – in zwei Varianten: Aufsatzrolläden (RNS, RNK/E, RNK/XT) und Vorsatzrolläden (RAK/E, RAS, RAR/E).',
    description: 'Rolläden an der Außenseite sind wichtige architektonische Elemente der Gebäudeausstattung. Sie dienen in erster Linie dem Schutz des Innenraums vor Einbruch. Darüber hinaus tragen sie zur zusätzlichen Isolierung von Fenstern und Balkontüren bei. Die richtige Auswahl gewährleistet dabei jahrelang höheren thermischen Komfort und Sicherheit.\n\nAufsatzrolläden (RNS, RNK/E, RNK/XT) werden während des Einbaus oder Austauschs von Fenstern installiert und sitzen direkt auf dem Blendrahmen. Vorsatzrolläden (RAK/E, RAS, RAR/E) können im Nachhinein montiert werden und lassen sich in die Gebäudefassade integrieren.\n\nAlle Varianten sind in zahlreichen Farben erhältlich und auf Maß gefertigt.',
    specs: [
      { label: 'Aufsatz 1', value: 'RNS' },
      { label: 'Aufsatz 2', value: 'RNK/E' },
      { label: 'Aufsatz 3', value: 'RNK/XT' },
      { label: 'Vorsatz 1', value: 'RAK/E' },
      { label: 'Vorsatz 2', value: 'RAS' },
      { label: 'Vorsatz 3', value: 'RAR/E' },
      { label: 'Fertigung', value: 'Maßanfertigung' },
    ],
    features: [
      'Aufsatzrolläden RNS, RNK/E, RNK/XT – Montage beim Fenstereinbau',
      'Vorsatzrolläden RAK/E, RAS, RAR/E – nachträgliche Montage möglich',
      'In Gebäudefassade integrierbar',
      'Einbruchschutz, Sonnenschutz und Wärmedämmung',
      'Maßanfertigung nach Kundenwunsch',
      'Zahlreiche Farben verfügbar',
    ],
    badges: [
      { type: 'german-market', label: 'Geeignet für den deutschen Markt' },
    ],
  },

  {
    id: 'steuerungssysteme',
    name: 'Steuerungssysteme',
    tagline: 'Smarte Steuerung für Fenster, Rolläden & Garagentore',
    category: 'Zubehör',
    badge: 'Smart Home',
    image: 'images/steuerungssysteme.png',
    imageContain: true,
    shortDesc: 'SOMFY Steuerungssysteme für Fenster, Rolläden, Terrassenmarkisen und Garagentore – per Wandschalter, Kabel, Fernbedienung oder Smartphone-App.',
    description: 'SOMFY sorgt dafür, dass das Leben zu Hause einfach und komfortabel ist, sodass Sie mehr Zeit für Ihre persönlichen Aktivitäten haben. Die Hochfahren von Außenrolläden und Terrassentüren von Markisen oder das Öffnen des Garagentors – all diese Geräte können mithilfe der intelligenten Systeme von SOMFY gesteuert werden.\n\nSOMFY SITUO bietet 1-Kanal-Fernbedienung in RTS-Technologie. SOMFY SMOOVE ist ein eleganter Origin 2 RTS Sender im Pure Frame Design. Die SMARTPHONE-Steuerung via IO Homecontrol ermöglicht komfortable und automatische Verwaltung mehrerer Geräte über Produktgruppen per Touchscreen. Mit TAHOMA Premium können alle Geräte und Sensoren in einem integrierten System kombiniert, gesteuert und Befehle zeitbasiert oder per Trigger ausgeführt werden.\n\nKompatibel mit Fenstern, Rolläden, Terrassenmarkisen und Garagentoren.',
    specs: [
      { label: 'System 1', value: 'SOMFY SITUO' },
      { label: 'System 2', value: 'SOMFY SMOOVE' },
      { label: 'System 3', value: 'Smartphone-App' },
      { label: 'System 4', value: 'TAHOMA Premium' },
      { label: 'Technologie', value: 'RTS / IO Homecontrol' },
      { label: 'Kompatibel', value: 'Fenster, Rolläden, Garagentor' },
    ],
    features: [
      'SOMFY SITUO – 1-Kanal-Fernbedienung (RTS)',
      'SOMFY SMOOVE – Wandsender im Pure Frame Design',
      'Smartphone-App – IO Homecontrol, Produktgruppen steuerbar',
      'TAHOMA Premium – zentrales Smart-Home-System',
      'Kompatibel mit Fenstern, Rolläden, Markisen und Garagentoren',
      'Zeitbasierte Automatisierung möglich',
    ],
    badges: [
      { type: 'german-market', label: 'Geeignet für den deutschen Markt' },
    ],
  },

  {
    id: 'raffstoren',
    name: 'Raffstoren',
    tagline: 'Moderner Sonnenschutz für architektonische Gebäude',
    category: 'Zubehör',
    badge: 'Sonnenschutz',
    image: 'images/raffstoren.png',
    imageContain: true,
    shortDesc: 'Raffstoren – modernes und elegantes Produkt für die Außenfassade. Lamellensysteme 290 & C80 sowie Befestigungssysteme für Unterputz- und Fassadeneinbau.',
    description: 'Raffstoren sind ein modernes und elegantes Produkt, das an der Außenseite der Hausfassade angebracht werden kann. Ihre leichte und elegante Bauweise eignet sich ideal für architektonische Gebäude mit großflächigen Verglasungen. In bis zu 11 Farben nach Vorlage erhältlich.\n\nDas Lamellensystem 290 bietet Z-förmige Lamellen mit einer Breite von 90 mm. Das System C80 arbeitet mit C-förmigen Lamellen mit einer Breite von 65 bzw. 80 mm.\n\nFür die Befestigung stehen verschiedene Systeme zur Verfügung: Solidbox Kasten 2.90 für die Unterputzmontage, die Bodenrinne des Solidbox Systems C-80, die Kasten BeCleVer 265 C-80 Installation in einer Fensterbox sowie die Unterputz- oder Fassadeneinbau Solid Box.',
    specs: [
      { label: 'System 1', value: 'Lamelle 290 (Z-förmig, 90 mm)' },
      { label: 'System 2', value: 'Lamelle C80 (C-förmig, 65/80 mm)' },
      { label: 'Befestigung 1', value: 'Solidbox Kasten 2.90' },
      { label: 'Befestigung 2', value: 'Bodenrinne Solidbox C-80' },
      { label: 'Befestigung 3', value: 'BeCleVer 265 C-80 Fensterbox' },
      { label: 'Farben', value: '11 Farben nach Vorlage' },
      { label: 'Montage', value: 'Unterputz oder Fassade' },
    ],
    features: [
      'Lamellensystem 290 – Z-förmige Lamellen, 90 mm Breite',
      'Lamellensystem C80 – C-förmige Lamellen, 65/80 mm Breite',
      'Solidbox Kasten 2.90 – Unterputzmontage',
      'Bodenrinne Solidbox C-80',
      'BeCleVer 265 C-80 – Installation in Fensterbox',
      'Unterputz- oder Fassadeneinbau möglich',
      '11 Farben nach Vorlage',
    ],
    badges: [
      { type: 'german-market', label: 'Geeignet für den deutschen Markt' },
    ],
  },

  {
    id: 'garagentore',
    name: 'Garagentore',
    tagline: 'Sicherheit, Bedienfreundlichkeit und Ästhetik',
    category: 'Zubehör',
    badge: 'Smart Home',
    image: 'images/garagentore.png',
    imageContain: true,
    shortDesc: 'Sektionaltore mit schmalen und breiten Lamellen oder Fertigung ohne Prägung – 12 RAL-Farben, Smart-Home-fähig. Thermische Isolierung für maximalen Komfort.',
    description: 'Das Garagentor gehört zu den wesentlichen Bestandteilen jedes modernen Hauses. Seine Hauptfunktionen sind Sicherheit, Bedienungsfreundlichkeit und Ästhetik. Bei wärmegedämmten Garagen ist auch die thermische Isolierung von Bedeutung. Jedes angebotene Tor lässt sich in ein Smart-Home-System integrieren.\n\nDie Paneltypen sind in drei Strukturvarianten erhältlich: schmale Lamellen, breite Lamellen und Fertigung ohne Prägung. Sektionaltore bieten die bequemste Lösung für Ihre Garage – mit einem Wärmedurchgangskoeffizienten von Uk = 1,07 [W/m²K], besonders gut geeignet für beheizte Garagen.\n\nIn bis zu 12 RAL-Farben erhältlich, darunter Anthrazit, Schwarz, JET BLACK, Turkischen Akazie, Dunkle Eiche, Türkei-Eschenmaui, Winchester, Goldene Eiche, Weihaus, Navu, Braun und Hofhout.',
    specs: [
      { label: 'Typ', value: 'Sektionaltor' },
      { label: 'Uk-Wert', value: '1,07 W/m²K' },
      { label: 'Panel 1', value: 'Schmale Lamellen' },
      { label: 'Panel 2', value: 'Breite Lamellen' },
      { label: 'Panel 3', value: 'Fertigung ohne Prägung' },
      { label: 'Farben', value: '12 RAL-Farben' },
      { label: 'Smart Home', value: 'Integrierbar' },
    ],
    features: [
      'Sektionaltor mit Uk-Wert 1,07 W/m²K',
      'Schmale Lamellen, breite Lamellen oder ohne Prägung',
      '12 RAL-Farben verfügbar',
      'Smart-Home-Integration möglich',
      'Thermische Isolierung für beheizte Garagen',
      'Hohe Sicherheit und Bedienfreundlichkeit',
    ],
    badges: [
      { type: 'german-market', label: 'Geeignet für den deutschen Markt' },
    ],
  },

  {
    id: 'glasscheibenpakete',
    name: 'Glasscheibenpakete',
    tagline: 'Das richtige Glas für jeden Anspruch',
    category: 'Zubehör',
    badge: 'Verglasung',
    image: 'images/glasscheibenpakete.png',
    imageContain: true,
    shortDesc: 'Glasscheibenpakete in 6 Varianten: Hoher Standard, Energiesparend, Schalldämmend, Einbruchschutz, Sicherheitsglas und Sonnenschutz.',
    description: 'Scheiben, die in Fenstern eingebaut werden, zeichnen sich durch vielfältige Aspekte aus. Bei der Auswahl von Fenstern lohnt es sich, alle Möglichkeiten genau zu analysieren.\n\nDas Glas mit hohem Standard bietet solide Grunddämmung für Standardanwendungen. Energiesparendes Glas minimiert den Wärmeverlust und senkt die Heizkosten dauerhaft. Schalldämmendes Glas sorgt für spürbare Ruhe im Innenraum. Einbruchschutzglas erhöht die Sicherheit und erschwert das Eindringen erheblich. Sicherheitsglas bricht bei Beschädigung in ungefährliche Bruchstücke. Sonnenschutzglas reduziert die Wärmeentwicklung im Innenraum bei maximaler Lichttransmission.\n\nAlle Glasscheibenpakete sind auf die Profilsysteme im Sortiment abgestimmt.',
    specs: [
      { label: 'Variante 1', value: 'Hoher Standard' },
      { label: 'Variante 2', value: 'Energiesparend' },
      { label: 'Variante 3', value: 'Schalldämmend' },
      { label: 'Variante 4', value: 'Einbruchschutz' },
      { label: 'Variante 5', value: 'Sicherheitsglas' },
      { label: 'Variante 6', value: 'Sonnenschutz' },
    ],
    features: [
      'Hoher Standard – solide Grunddämmung',
      'Energiesparend – minimierter Wärmeverlust, niedrigere Heizkosten',
      'Schalldämmend – spürbare Lärmreduzierung im Innenraum',
      'Einbruchschutz – erschwertes Eindringen',
      'Sicherheitsglas – sicheres Bruchverhalten',
      'Sonnenschutz – reduzierte Wärmeentwicklung bei maximaler Lichttransmission',
    ],
    badges: [
      { type: 'german-market', label: 'Geeignet für den deutschen Markt' },
    ],
  },

  {
    id: 'ornamentglas',
    name: 'Ornamentglas',
    tagline: 'Sichtschutz mit dekorativem Charakter',
    category: 'Zubehör',
    badge: 'Dekor',
    image: 'images/ornamentglas.png',
    imageContain: true,
    shortDesc: '18 Ornamentglas-Muster für Fenster und Türen – von Kathedral über Chinchilla bis Diamante. Ideal für Flure und Badezimmer.',
    description: 'Das Angebot an Isolierverglasungen wird durch eine breite Auswahl an Ornamentgläsern ergänzt. Mit diesen Ornamenten können verschiedene Muster wie Regen, Raureif oder Nebel in den Fenstern gestaltet werden. Ornamentglas wird vor allem in Fluren und Badezimmern verwendet.\n\nZur Auswahl stehen 18 verschiedene Muster: Delta Piask, Delta, FL Mat, Atlantic, Diamante 9, Altdeutsch K, Flutes 88, Flutes Piask, Kathedral, Cremi, Kura, Master-Ligne, Master-Point, Master-Carré, Niagara, Screen, Silvit und Chinchilla.\n\nAlle Ornamentgläser sind als Isolierverglasung erhältlich und mit den gängigen Profilsystemen kombinierbar.',
    specs: [
      { label: 'Muster', value: '18 verschiedene Designs' },
      { label: 'Anwendung', value: 'Flure, Badezimmer, Trennwände' },
      { label: 'Verglasung', value: 'Isolierverglasung' },
      { label: 'Effekte', value: 'Regen, Raureif, Nebel u.v.m.' },
    ],
    features: [
      'Delta Piask, Delta, FL Mat, Atlantic',
      'Diamante 9, Altdeutsch K',
      'Flutes 88, Flutes Piask, Kathedral, Cremi',
      'Kura, Master-Ligne, Master-Point, Master-Carré',
      'Niagara, Screen, Silvit, Chinchilla',
      'Als Isolierverglasung erhältlich',
    ],
    badges: [
      { type: 'german-market', label: 'Geeignet für den deutschen Markt' },
    ],
  },

  {
    id: 'sonnenbestaendiges-glas',
    name: 'Sonnenbeständiges Glas',
    tagline: 'Solar Control für optimales Raumklima',
    category: 'Zubehör',
    badge: 'Solar Control',
    image: 'images/sonnenbestaendiges-glas.png',
    imageContain: true,
    shortDesc: 'SOLAR CONTROL Glas reduziert Wärmestrahlung, blockiert UV-Strahlen und hält Räume kühler – in 8 Varianten: Anistol & Stopsol in Blau, Grün, Grau, Klar und Braun.',
    description: 'SOLAR CONTROL Glas sorgt für eine optimale Raumtemperatur, reduziert die Lüftungskosten und blockiert UV-Strahlen weitgehend. Sonnenbeständiges Glas ermöglicht die gleichzeitige Aufrechterhaltung einer hohen Lichttransluzenz und eine deutliche Reduzierung der Durchlässigkeit wärmeformischer Energie.\n\nDas Sortiment umfasst zwei Produktlinien: ANISTOL und STOPSOL – jeweils in verschiedenen Farbtönen erhältlich:\n\nANISTOL: Blau 4mm, Grün 4mm, Grau 4mm, Braun 4mm\nSTOPSOL: SS Blau 6mm, Grün 6mm, Klar 4mm, Grau 4mm\n\nAlle Varianten sind als Isolierverglasung verfügbar und mit den gängigen Profilsystemen kombinierbar.',
    specs: [
      { label: 'Linie 1', value: 'ANISTOL (Blau, Grün, Grau, Braun)' },
      { label: 'Linie 2', value: 'STOPSOL (Blau, Grün, Klar, Grau)' },
      { label: 'Technologie', value: 'SOLAR CONTROL' },
      { label: 'Funktion', value: 'UV-Schutz, Wärmereduzierung' },
      { label: 'Verglasung', value: 'Isolierverglasung' },
      { label: 'Stärken', value: '4 mm / 6 mm' },
    ],
    features: [
      'ANISTOL Blau, Grün, Grau, Braun – je 4 mm',
      'STOPSOL SS Blau 6mm, Grün, Klar, Grau',
      'Blockiert UV-Strahlen weitgehend',
      'Reduziert Wärmedurchlässigkeit bei hoher Lichttransluzenz',
      'Senkt Lüftungs- und Kühlkosten',
      'Als Isolierverglasung erhältlich',
    ],
    badges: [
      { type: 'german-market', label: 'Geeignet für den deutschen Markt' },
    ],
  },

  {
    id: 'sprossen',
    name: 'Sprossen',
    tagline: 'Klassisches Erscheinungsbild für Neubau und Sanierung',
    category: 'Zubehör',
    badge: 'Dekor',
    image: 'images/sprossen.png',
    imageContain: true,
    shortDesc: 'Sprossen unterteilen die Glasfläche optisch in kleinere Teile – in 4 Varianten: Innenliegende, Aufgeklebte, Glasteilende und Wiener Sprossen.',
    description: 'Sprossen sind eine elegante Verzierung, die die Glasfläche optisch in kleinere Teile unterteilt. Fenster mit Sprossen wirken am besten in Gebäuden im Landhausstil aus. Solche Fenster verleihen dem Gebäude ein klassisches, interessantes und elegantes Aussehen.\n\nInnenliegende Sprossen befinden sich zwischen den Glasscheiben der Isolierverglasung und sind wartungsfrei. Aufgeklebte Sprossen werden auf der Glasoberfläche befestigt und imitieren echte Sprossenteilung. Glasteilende Sprossen unterteilen die Verglasung tatsächlich in separate Scheiben für ein authentisches Erscheinungsbild. Wiener Sprossen sind eine besonders elegante Variante mit feinem Profil im Wiener Stil.\n\nAlle Sprossenvarianten sind mit den gängigen Kunststoff- und Aluminiumprofilsystemen kombinierbar.',
    specs: [
      { label: 'Variante 1', value: 'Innenliegende Sprossen' },
      { label: 'Variante 2', value: 'Aufgeklebte Sprossen' },
      { label: 'Variante 3', value: 'Glasteilende Sprossen' },
      { label: 'Variante 4', value: 'Wiener Sprossen' },
      { label: 'Stil', value: 'Landhaus, klassisch, elegant' },
      { label: 'Kompatibel', value: 'Kunststoff & Aluminium' },
    ],
    features: [
      'Innenliegende Sprossen – wartungsfrei zwischen den Scheiben',
      'Aufgeklebte Sprossen – optische Sprossenteilung',
      'Glasteilende Sprossen – echte Scheibenteilung',
      'Wiener Sprossen – elegantes Feinprofil',
      'Klassisches Landhausdesign',
      'Kombinierbar mit Kunststoff- und Aluminiumfenstern',
    ],
    badges: [
      { type: 'german-market', label: 'Geeignet für den deutschen Markt' },
    ],
  },

  {
    id: 'sprossenarten',
    name: 'Sprossenarten',
    tagline: 'Vielfalt in Farbe, Breite und Material',
    category: 'Zubehör',
    badge: 'Zubehör',
    image: 'images/sprossenarten.png',
    imageContain: true,
    shortDesc: 'Sprossprofile in RAL-Farben und Holzdekoren – Breiten von 6 bis 45 mm. Weiß, Golden, Nussbaum, Mahagoni, Eiche und mehr. Biegbar für Bögen und Winkel.',
    description: 'Die Sprossen unserer Fenster sind in einer großen Auswahl an RAL-Farben erhältlich – auch zweifarbig. Unser Angebot umfasst Profile mit einer Breite von 6, 16, 24 und 45 mm. Diese Elemente lassen sich wahlweise zu Bögen oder Kreisen biegen und auch in unterschiedlichen Winkeln verbinden.\n\nZur Auswahl stehen folgende Varianten: Weiß 6mm, Golden 6mm, 1808 Weiß 9010, 1808 Golden, 1808 Dunkle Eiche, 1808 Goldene Eiche, 1808 Nussbaum, 1808 Mooreiche, 1808 Mahagoni, 2408 Weiß 9010, 4508 Weiß 9010 sowie 2408 Duplex.\n\nAlle Sprossenprofile sind mit den gängigen Kunststoff- und Aluminiumfenstersystemen kombinierbar.',
    specs: [
      { label: 'Breiten', value: '6, 16, 24, 45 mm' },
      { label: 'Farben', value: 'RAL, auch zweifarbig' },
      { label: 'Dekore', value: 'Weiß, Golden, Eiche, Nussbaum, Mahagoni' },
      { label: 'Formen', value: 'Gerade, Bogen, Winkel' },
      { label: 'Kompatibel', value: 'Kunststoff & Aluminium' },
    ],
    features: [
      'Weiß 6mm, Golden 6mm',
      '1808: Weiß 9010, Golden, Dunkle Eiche, Goldene Eiche',
      '1808: Nussbaum, Mooreiche, Mahagoni',
      '2408 Weiß 9010, 4508 Weiß 9010, 2408 Duplex',
      'Biegbar für Bögen und Kreise',
      'Auch zweifarbig in RAL-Farben erhältlich',
    ],
    badges: [
      { type: 'german-market', label: 'Geeignet für den deutschen Markt' },
    ],
  },

  {
    id: 'kopplungsarten',
    name: 'Kopplungsarten',
    tagline: 'Großflächige Fensterkonstruktionen flexibel verbinden',
    category: 'Zubehör',
    badge: 'Zubehör',
    image: 'images/kopplungsarten.png',
    imageContain: true,
    shortDesc: 'Drei Kopplungsarten für großflächige Fensteranlagen: Federkopplung, Statische Kopplung und Rohrkopplung – für sichere und optisch saubere Verbindungen.',
    description: 'Fenstern werden durch die moderne Architektur oft immer höheren Anforderungen gestellt. Sehr große Fensterlösungen werden immer beliebter. Es werden sowohl sinnvolle, beweisliche als auch stilistisch Verglaserglücke eingesetzt. Wir bieten eine breite Palette von Fensterkopplungsprofilen, die ungehinderte Montagen von mehreren Elementen ermöglichen.\n\nDie Federkopplung basiert auf Profil Ideal 4000 Tür Inne (140x20) mit Stahlverstärkung und Federkopplug (22016). Die Statische Kopplung verwendet Profil Ideal 4000 Stille (140x20) mit Stahlverstärkung und Brücke Kopplung 21 Inn (140318). Die Rohrkopplung nutzt Profil Ideal 4000 Grill Inne (140x20) mit Stahlverstärkung und einer Rohr-Kopplung (140342 + 140344) mit Stahlverstärkung.\n\nAlle Kopplungsarten ermöglichen die ungehinderte Montage von mehreren Fensterelementen zu großflächigen Konstruktionen.',
    specs: [
      { label: 'Kopplung 1', value: 'Federkopplung' },
      { label: 'Kopplung 2', value: 'Statische Kopplung' },
      { label: 'Kopplung 3', value: 'Rohrkopplung' },
      { label: 'Basis', value: 'Profil Ideal 4000' },
      { label: 'Verstärkung', value: 'Stahlverstärkung' },
      { label: 'Anwendung', value: 'Großflächige Fensterkonstruktionen' },
    ],
    features: [
      'Federkopplung – flexibel, mit Federkopplungsprofil (22016)',
      'Statische Kopplung – fest, mit Brücke Kopplung 21 Inn (140318)',
      'Rohrkopplung – Rohr-Kopplung (140342 + 140344)',
      'Alle auf Basis Profil Ideal 4000',
      'Stahlverstärkung für maximale Stabilität',
      'Für großflächige Mehrelement-Fensterkonstruktionen',
    ],
    badges: [
      { type: 'german-market', label: 'Geeignet für den deutschen Markt' },
    ],
  },

  {
    id: 'fenstergriffe',
    name: 'Fenstergriffe',
    tagline: 'Stil und Funktion für jeden Fenstertyp',
    category: 'Zubehör',
    badge: 'Zubehör',
    image: 'images/fenstergriffe.png',
    imageContain: true,
    shortDesc: '4 Griffserien in je 5 Farben: HOPPE Atlanta, Toulon, Hamburg und ROTOSWING – in Weiß, Silber, Inox, Schwarz matt, Dunkelbraun und Gold.',
    description: 'Fenstergriffe vereinen Stil und Funktion und sind in vier hochwertigen Serien erhältlich, die sich jeweils in bis zu fünf Farben anbieten.\n\nHOPPE ATLANTA: F9016 Weiß, F1 Silber, F9 Inox, F870 Dunkelbraun, F4 Gold-Braun\nHOPPE TOULON: F9016 Weiß, F1 Silber, F9 Inox, F9Fn Schwarz Matte, F4 Gold-Braun\nHOPPE HAMBURG: F9016 Weiß, F1 Silber, F9 Inox, F9Fn Schwarz Matte, F4 Gold-Braun\nROTOSWING: R072 Weiß, R077 Silber, R040 Inox, R046 Braun, R063-N2 Gold\n\nAlle Griffe sind passend für die gängigen Kunststoff- und Aluminiumfensterprofile erhältlich.',
    specs: [
      { label: 'Serie 1', value: 'HOPPE ATLANTA' },
      { label: 'Serie 2', value: 'HOPPE TOULON' },
      { label: 'Serie 3', value: 'HOPPE HAMBURG' },
      { label: 'Serie 4', value: 'ROTOSWING' },
      { label: 'Farben', value: 'Weiß, Silber, Inox, Schwarz, Gold' },
      { label: 'Kompatibel', value: 'Kunststoff & Aluminium' },
    ],
    features: [
      'HOPPE ATLANTA – klassisch, in 5 Farben',
      'HOPPE TOULON – modern, in 5 Farben inkl. Schwarz matt',
      'HOPPE HAMBURG – ergonomisch, in 5 Farben',
      'ROTOSWING – geschwungen, in 5 Farben inkl. Gold',
      'Passend für alle gängigen Fensterprofile',
      'Hochwertige Oberflächenveredelung',
    ],
    badges: [
      { type: 'german-market', label: 'Geeignet für den deutschen Markt' },
    ],
  },

  {
    id: 'beschlaege',
    name: 'Beschläge',
    tagline: 'Sicherheit, Komfort und Funktion für jedes Fenster',
    category: 'Zubehör',
    badge: 'Sicherheit',
    image: 'images/beschlaege.png',
    imageContain: true,
    shortDesc: 'Komplettes Beschlagsortiment: Fehlbedienungssperre, Öffnungsbegrenzer, Schließblech, Kontaktron, Balkonschnäpper, Activpilot und mehr.',
    description: 'Eine der wesentlichen Komponenten, aus denen ein Fenster besteht, ist der Beschlag. Er setzt sich aus einer Reihe von beweglichen Teilen zusammen, die im Flügel versteckt sind. Der Beschlag erfüllt mehrere Funktionen: Er regelt die Lüftungsgrade, hält den Flügel in der gewünschten Position und schützt vor versehentlichen Zuziehen beim Durchzug.\n\nFehlbedienungssperre verhindert das Schieben des Flügels aus dem Rahmen. Öffnungsbegrenzer begrenzt das Öffnungsmaß und kontrolliert den Öffnungsgrad des Fensters. Schließblech verhindert das Aufbrechen des Fensterfügels. Verdeckte Beschläge sorgen für bessere Ästhetik des Fensters. Kontaktron meldet den Einbruchsversuch. Balkonschnäpper ermöglicht das Zuschließen der Balkontüre von außen.\n\nActivpilot Comfort Pack und Activpilot Giant ermöglichen den Zugang zum Fenster (260mm, 365mm, 490mm, 570mm) mit versenktem Griff. Easypilot Soleil ist ein Zentraler Griff für große und schwere Fenster.',
    specs: [
      { label: 'Sicherheit', value: 'Fehlbedienungssperre, Schließblech' },
      { label: 'Komfort', value: 'Öffnungsbegrenzer, Balkonschnäpper' },
      { label: 'Smart', value: 'Kontaktron (Einbruchmeldung)' },
      { label: 'Design', value: 'Verdeckte Beschläge' },
      { label: 'Großfenster', value: 'Activpilot Giant, Easypilot Soleil' },
      { label: 'Komfort Pack', value: 'Activpilot Comfort Pack' },
    ],
    features: [
      'Fehlbedienungssperre – verhindert Herausschieben des Flügels',
      'Öffnungsbegrenzer – kontrollierter Lüftungsspalt',
      'Schließblech – Einbruchschutz',
      'Kontaktron – elektronische Einbruchmeldung',
      'Balkonschnäpper – Balkontür von außen schließbar',
      'Activpilot Comfort Pack & Giant – für große und schwere Fenster',
      'Easypilot Soleil – zentraler Griff für Großformate',
      'Verdeckte Beschläge für cleanes Design',
    ],
    badges: [
      { type: 'german-market', label: 'Geeignet für den deutschen Markt' },
    ],
  },

  {
    id: 'sicherheitssysteme',
    name: 'Sicherheitssysteme',
    tagline: 'RC2-Einbruchschutz für Fenster und Türen',
    category: 'Zubehör',
    badge: 'RC2',
    image: 'images/sicherheitssysteme.png',
    imageContain: true,
    shortDesc: 'Einbruchschutz nach RC1–RC2: Sicherheitsbeschlag, RC2-Fenstergriff mit Schlüssel und Sicherheitsglas EN 356 – für maximalen Schutz vor Einbruch.',
    description: 'Die Sicherheit von Fenstern ist eine der wichtigsten Eigenschaften für Benutzer. Daher ist es wichtig, dass die Fensterverriegelung den entsprechenden Sicherheitsstandards entspricht. Das Konzept des einbruchsicheren Fensters definiert maximale Hindernisse für den Zugang zum Haus, auch für potenzielle Einbrecher.\n\nDie Sicherheitsbeschläge schützen Fenster vor Einbruch durch physische Gewalt, bieten jedoch begrenzten Schutz gegen Einbruch durch Werkzeuge, mit denen der Flügel gehebelt werden kann. RC2-Beschläge schützen Fenster vor Einbruch durch einfache Werkzeuge wie Schraubendreher, Zange und Kelle, die dazu verwendet werden können, den geschlossenen und verriegelten Flügel zu öffnen.\n\nFensterelemente mit RC2-Einbruchsbeständigkeit umfassen: Sicherheitsbeschlag (wird rund um das Fenster mit achteckigen Verriegelungspfeilern und Diebstahlsicherungen ausgestattet), Fenstergriff mit Schlüssel (verhindert unbefugtes Öffnen von Rahmenscheiben) sowie Sicherheitsglas nach EN 356, Klasse P4A.',
    specs: [
      { label: 'Klasse', value: 'RC1 – RC2' },
      { label: 'Beschlag', value: 'Achteckige Verriegelungspfeiler' },
      { label: 'Griff', value: 'Fenstergriff mit Schlüssel' },
      { label: 'Glas', value: 'Sicherheitsglas EN 356, P4A' },
      { label: 'Schutz', value: 'Gegen Werkzeug & Hebeln' },
    ],
    features: [
      'RC2-zertifizierter Sicherheitsbeschlag',
      'Achteckige Verriegelungspfeiler rund ums Fenster',
      'Fenstergriff mit Schlüssel gegen unbefugtes Öffnen',
      'Sicherheitsglas EN 356, Klasse P4A',
      'Schutz gegen Schraubendreher, Zange und Hebelwerkzeug',
      'Für Erdgeschoss- und gefährdete Fenster empfohlen',
    ],
    badges: [
      { type: 'german-market', label: 'Geeignet für den deutschen Markt' },
      { type: 'rc2', label: 'RC2 Einbruchschutz' },
    ],
  },

  {
    id: 'dekoren',
    name: 'Dekoren',
    tagline: 'Individuelle Farb- und Foliengestaltung für Fensterprofile',
    category: 'Zubehör',
    badge: 'Dekore',
    image: 'images/dekoren.png',
    imageContain: true,
    shortDesc: 'Fensterprofile in einer Vielzahl von Farben und Dekoren – von Weiß über Holzoptiken bis hin zu Anthrazit und Pastelltönen für individuelle Gestaltung.',
    description: 'Dank der Vielförmung von Fensterprofilen in einer Vielzahl von Farben ist es möglich, die Fensterverkleidung an die individuellen Wünsche der Kunden anzupassen.\n\nOb klassisches Weiß, edle Holzoptik oder moderne Anthrazittöne – das umfangreiche Dekorsortiment bietet für jeden Geschmack und jede Architektur die passende Lösung. Die hochwertigen Dekorfolien sind UV-beständig, pflegeleicht und dauerhaft farbtreu.\n\nVon hellen Pastelltönen über natürliche Holzmuster bis hin zu kräftigen Farben wie Dunkelgrün oder Rotbraun: Die Dekorvielfalt erlaubt es, Fenster harmonisch in die Fassadengestaltung zu integrieren oder gezielt Akzente zu setzen.',
    specs: [
      { label: 'Farbtöne', value: 'Weiß, Holzoptik, Anthrazit, Pastell u.v.m.' },
      { label: 'Oberfläche', value: 'UV-beständige Dekorfolie' },
      { label: 'Pflege', value: 'Pflegeleicht, dauerhaft farbtreu' },
      { label: 'Anwendung', value: 'Alle Fenster- und Türprofile' },
    ],
    features: [
      'AP02 – Cremeweiß',
      'AP60 – Anthrazit Satinglanz',
      'AP65 – Gransgrau (Steinstruktur)',
      'AP41 – Blau Matt',
      'AP42 – Brillantblau / Stahlgrau',
      'AP66 – Peters Grün',
      'AP67 – Nussgrau',
      'AP79 – Olive DB',
      'AP96 – Haselnussbraun',
      'AP25 – Sheffield Eiche Braun / Grau',
      'AP75 – Helle Sheffield Eiche',
      'AP91 – Lichte Eiken',
      'Eiche, Nußbraun, Sandgrau, Schwarz – Naturoptiken',
      'Aluminium Silberbedect – Metalliceffekt',
    ],
    badges: [
      { type: 'german-market', label: 'Geeignet für den deutschen Markt' },
    ],
  },

];
