const PRODUCTS = [

  // ── KUNSTSTOFF ──────────────────────────────────────────────────────────────

  {
    id: 'ideal-8000',
    name: 'IDEAL 8000',
    tagline: 'Das Passivhaus-Fenster',
    category: 'Kunststoff',
    badge: 'Bestseller',
    image: 'images/ideal-8000.png',
    imageContain: true,
    gallery: [
      'images/ideal-8000.png',
    ],
    shortDesc: 'Höchste Energieeffizienz für Neubauten und anspruchsvolle Sanierungen. Passivhaus-geeignet, RC2 Einbruchschutz, 6 Kammern, 3 Dichtungen.',
    description: 'Die ENERGIESPARENDEN Fenster im Fenstersystem IDEAL 8000 sind eine Kombination modernster technischer Lösungen, die Wärme, Ruhe und Sicherheit garantieren. Diese Fenster sind für Investoren konzipiert, die an sicherem, energieeffizientem und passivem Bauen interessiert sind.\n\nMit einem Uw-Wert von nur 0,76 W/m²K erfüllt das IDEAL 8000 alle Anforderungen des Passivhausstandards und bietet gleichzeitig zertifizierten Einbruchschutz der Klasse RC2. Durch die 6-Kammer-Konstruktion und 3 umlaufende Dichtungen erreicht das Profil eine Bautiefe von 85 mm – für optimale Wärmedämmung auch bei extremen Klimabedingungen.\n\nMit über 38 verfügbaren Dekorfolien lässt es sich individuell an jede Architektursprache anpassen. Ideal für Neubauten, Passivhäuser und hochwertige Sanierungen – wenn keine Kompromisse beim Energiestandard gemacht werden dürfen.',
    specs: [
      { label: 'Uw-Wert', value: '0,76* W/m²K' },
      { label: 'Bautiefe', value: '85 mm' },
      { label: 'Kammern', value: '6' },
      { label: 'Dichtungen', value: '3 umlaufend' },
      { label: 'Einbruchschutz', value: 'RC2' },
      { label: 'Standard', value: 'Passivhaus' },
      { label: 'Dekore', value: '38 Sorten' },
      { label: 'Verglasung', value: '3-fach' },
    ],
    specsNote: '* Der Uw-Wert betrifft das Referenzfenster mit dem Maß 1230×1480 mm, der 3-fach Verglasung mit warmer Kante und Ug-Wert 0,5 W/m²K.',
    features: [
      'Passivhaus-geeignet (zertifiziert)',
      'Einbruchschutz Klasse RC2',
      '6 Kammern, 3 umlaufende Dichtungen',
      'Bis zu 38 Dekorfolien verfügbar',
      'CE-zertifiziert',
      'Für Neubau und Sanierung geeignet',
    ],
    badges: [
      { type: 'german-market', label: 'Geeignet für den deutschen Markt' },
      { type: 'passivhaus', label: 'Passivhaus' },
      { type: 'rc2', label: 'RC2 Einbruchschutz' },
    ],
    variants: [
      { name: 'Classic Line', color: '#ffffff', border: '#d1d5db', profile: '180×05' },
      { name: 'Standard', color: '#7B4A2D', border: '#7B4A2D', profile: '180×05' },
      { name: 'Anthrazit', color: '#3C3C3C', border: '#3C3C3C', profile: '180×20' },
    ],
  },

  {
    id: 'ideal-7000',
    name: 'IDEAL 7000',
    tagline: 'Premium ENERGO-Fenster',
    category: 'Kunststoff',
    badge: 'Energie A+',
    image: 'images/produkt-2-ideal7000.png',
    gallery: [
      'images/produkt-2-ideal7000.png',
      'images/produkt-2-ideal7000-2.png',
    ],
    shortDesc: 'Premiumfenster ENERGO auf Basis des IDEAL 7000-Profils. RC2 Einbruchschutz, 6 Kammern, 85 mm Bautiefe – ideal für moderne Einfamilienhäuser.',
    description: 'Premiumfenster ENERGO, die auf Basis des IDEAL 7000-Profils hergestellt werden, sind ein Beispiel für die Kombination der Eigenschaften von Profil und Isolierglas, um Fenster mit sehr niedrigem Wärmedurchgangskoeffizienten zu schaffen. Vor allem in modernen Einfamilienhäusern ist dies eine hervorragende Wahl.\n\nMit einem Uw-Wert von 0,79 W/m²K, 6 Kammern und 85 mm Bautiefe bietet das IDEAL 7000 hervorragende Wärmedämmeigenschaften bei gleichzeitigem Einbruchschutz der Klasse RC2. Das 3-fach Glaspaket sorgt für optimale Schall- und Wärmedämmung.\n\nMit bis zu 38 Dekorfolien lässt sich das Profil individuell an jede Architektursprache anpassen – in Standardweiß oder mit anthrazitgrauem Kern.',
    specs: [
      { label: 'Uw-Wert', value: '0,79* W/m²K' },
      { label: 'Bautiefe', value: '85 mm' },
      { label: 'Kammern', value: '6' },
      { label: 'Dichtungen', value: '2 umlaufend' },
      { label: 'Einbruchschutz', value: 'RC2' },
      { label: 'Glaspaket', value: '3-fach' },
      { label: 'Dekore', value: '38 Sorten' },
      { label: 'Zertifizierung', value: 'CE' },
    ],
    specsNote: '* Der Uw-Wert betrifft das Referenzfenster mit dem Maß 1230×1480 mm und der 2-fach Verglasung mit warmer Kante und Ug-Wert 1,1 W/m²K.',
    features: [
      'Einbruchschutz Klasse RC2',
      '6 Kammern, 2 umlaufende Dichtungen',
      '85 mm Bautiefe',
      '3-fach Glaspaket',
      'Bis zu 38 Dekorfolien verfügbar',
      'CE-zertifiziert',
      'Ideal für moderne Einfamilienhäuser',
    ],
    badges: [
      { type: 'rc2', label: 'RC2 Einbruchschutz' },
      { type: 'ce', label: 'CE-zertifiziert' },
    ],
    variants: [
      { name: 'Standard', color: '#ffffff', border: '#d1d5db', profile: '170×02 / 170×20' },
      { name: 'Anthrazitgrauer Kern', color: '#3C3C3C', border: '#3C3C3C', profile: '170×02 / 170×20' },
    ],
  },

  {
    id: 'neo',
    name: 'NEO – New Look',
    tagline: 'Zeitlos kubisches Design',
    category: 'Kunststoff',
    badge: 'Design',
    image: 'images/produkt-3-neo.png',
    gallery: [
      'images/produkt-3-neo.png',
      'images/produkt-3-neo-2.png',
    ],
    shortDesc: 'Zeitloses kubisches Design mit symmetrischer Profilform. ift Rosenheim zertifiziert, 6 Kammern, 76 mm Bautiefe.',
    description: 'Die NEW LOOK Fenster sind ein äußerst attraktives Designangebot für Kunden, die Wert auf einen zeitlosen Stil legen. Die symmetrische, kubistische Form ist das charakteristische Merkmal der Fenster im NEO-System. Die NEW LOOK Fenster sind ein schlichtes und schönes Design für jedes Zuhause. Sie schaffen eine harmonische Verbindung zwischen Innen- und Außenelementen, wodurch der Raum heller und einladender wirkt.\n\nMit einem Uw-Wert von 0,78 W/m²K und einer Bautiefe von 76 mm bietet das NEO hervorragende Wärmedämmeigenschaften bei schmalem Profil. Das Profil ist mit 2- oder 3-fach Glaspaket sowie 2 oder 3 Dichtungen erhältlich und passt sich so optimal an unterschiedliche Anforderungen an.\n\nMit bis zu 38 Dekorfolien lässt sich das NEO individuell gestalten – ein schlichtes und schönes Design für jedes Zuhause.',
    specs: [
      { label: 'Uw-Wert', value: '0,78* W/m²K' },
      { label: 'Bautiefe', value: '76 mm' },
      { label: 'Kammern', value: '6' },
      { label: 'Dichtungen', value: '2 o. 3' },
      { label: 'Glaspaket', value: '2- o. 3-fach' },
      { label: 'Dekore', value: '38 Sorten' },
      { label: 'Zertifizierung', value: 'ift Rosenheim + CE' },
    ],
    specsNote: '* Der Uw-Wert betrifft das Referenzfenster NEO MD mit dem Maß 1230×1480 mm und der 2-fach Verglasung mit warmer Kante und Ug-Wert 1,0 W/m²K.',
    features: [
      'Symmetrisches, kubisches Profil',
      'Harmonische Verbindung Innen- und Außenbereich',
      '6 Kammern, 76 mm Bautiefe',
      '2- oder 3-fach Glaspaket wählbar',
      '2 oder 3 Dichtungen',
      'Bis zu 38 Dekorfolien',
      'ift Rosenheim zertifiziert',
      'CE-zertifiziert',
    ],
    badges: [
      { type: 'ift', label: 'ift Rosenheim zertifiziert' },
      { type: 'ce', label: 'CE-zertifiziert' },
    ],
    variants: [
      { name: 'NEO MD', color: '#ffffff', border: '#d1d5db', profile: '160×07 / 160×20' },
      { name: 'NEO AD', color: '#C4A882', border: '#C4A882', profile: '160×01 / 160×20' },
    ],
  },

  {
    id: 'ideal-4000',
    name: 'IDEAL 4000',
    tagline: 'Universal ECO-Fenster',
    category: 'Kunststoff',
    image: 'images/produkt-4-ideal4000.png',
    gallery: [
      'images/produkt-4-ideal4000.png',
      'images/produkt-4-ideal4000-2.png',
    ],
    shortDesc: 'UNIVERSAL ECO-Fenster in klassischer und runder Profillinie. Perfekte Balance aus Ökonomie und Ökologie – ift Rosenheim zertifiziert.',
    description: 'UNIVERSAL ECO-Fenster, basierend auf dem IDEAL 4000 Profil, bieten die perfekte Balance zwischen klassischem Design und den funktionalen Aspekten modernster Bautechnologien. Die UNIVERSAL ECO-Fenster, die in zwei Profiltypen (klassisch und rund) sowie in Drei- und Doppelglaspaketen angeboten werden, gewährleisten die optimale Kombination von Ökonomie und Ökologie.\n\nMit 5 Kammern, 2 Dichtungen und einer Bautiefe von 70 mm ist das IDEAL 4000 eine solide und langlebige Wahl für Wohngebäude, Mehrfamilienhäuser und Sanierungsprojekte. Die ift Rosenheim-Zertifizierung belegt die geprüfte Qualität nach europäischem Standard.\n\nMit bis zu 38 Dekorfolien lässt es sich individuell gestalten.',
    specs: [
      { label: 'Uw-Wert', value: '1,28* W/m²K' },
      { label: 'Bautiefe', value: '70 mm' },
      { label: 'Kammern', value: '5' },
      { label: 'Dichtungen', value: '2 umlaufend' },
      { label: 'Glaspaket', value: '2- o. 3-fach' },
      { label: 'Dekore', value: '38 Sorten' },
      { label: 'Zertifizierung', value: 'ift Rosenheim + CE' },
    ],
    specsNote: '* Der Uw-Wert betrifft das Referenzfenster mit dem Maß 1230×1480 mm und der 2-fach Verglasung mit warmer Kante und Ug-Wert 1,1 W/m²K.',
    features: [
      '5 Kammern, 70 mm Bautiefe',
      '2 umlaufende Dichtungen',
      '2- oder 3-fach Glaspaket wählbar',
      'Classic Line und Round-Line verfügbar',
      'Bis zu 38 Dekorfolien',
      'ift Rosenheim zertifiziert',
      'CE-zertifiziert',
    ],
    badges: [
      { type: 'ift', label: 'ift Rosenheim zertifiziert' },
      { type: 'ce', label: 'CE-zertifiziert' },
    ],
    variants: [
      { name: 'Classic Line', color: '#ffffff', border: '#d1d5db', profile: '140×01 / 140×20' },
      { name: 'Round-Line', color: '#f3f4f6', border: '#d1d5db', profile: '140×01 / 140×22' },
    ],
  },

  {
    id: 'ideal-5000',
    name: 'IDEAL 5000',
    tagline: 'Das vielseitige Mittelklasse-Fenster',
    category: 'Kunststoff',
    badge: 'Beliebt',
    image: 'images/produkt-5-ideal5000.png',
    gallery: [
      'images/produkt-5-ideal5000.png',
      'images/produkt-5-ideal5000-2.png',
    ],
    shortDesc: 'Die ausgezeichneten Dämmeigenschaften des IDEAL 5000 garantieren erstklassigen Wohnkomfort. ift Rosenheim zertifiziert, 5 Kammern, 70 mm Bautiefe.',
    description: 'Die ausgezeichneten Dämmeigenschaften des IDEAL 5000 garantieren erstklassigen Wohnkomfort. Die hochwertigen Profilsysteme von ALUPLAST gewährleisten zudem hervorragenden Einbruchschutz und somit ein beruhigendes Maß an Sicherheit.\n\nMit 5 Kammern, 3 umlaufenden Dichtungen und einer Bautiefe von 70 mm bietet das IDEAL 5000 eine solide und bewährte Lösung für Wohngebäude, Mehrfamilienhäuser und Sanierungsprojekte. Das 2- oder 3-fach Glaspaket ist frei wählbar.\n\nDas Profil ist in 5 hochwertigen Folienvarianten erhältlich – von klassisch Weiß über Golden Eiche bis hin zu modernem Jetblack Tiefschwarz.',
    specs: [
      { label: 'Uw-Wert', value: '1,23* W/m²K' },
      { label: 'Bautiefe', value: '70 mm' },
      { label: 'Kammern', value: '5' },
      { label: 'Dichtungen', value: '3 umlaufend' },
      { label: 'Glaspaket', value: '2- o. 3-fach' },
      { label: 'Dekore', value: '5 Sorten' },
      { label: 'Zertifizierung', value: 'ift Rosenheim + CE' },
    ],
    specsNote: '* Wärmedämmungskoeffizient eines Fensters Referenzabmessungen 1230×1480 mm, unter Verwendung einer Glasscheibe mit einem heißen Rahmen mit dem Koeffizienten Ug=1,1 W/m²K 4/16/4.',
    features: [
      '5 Kammern, 70 mm Bautiefe',
      '3 umlaufende Dichtungen',
      '2- oder 3-fach Glaspaket wählbar',
      '5 Foliensorten: Weiß, Golden Eiche, Anthrazit, Sandgrau, Jetblack',
      'ift Rosenheim zertifiziert',
      'CE-zertifiziert',
    ],
    badges: [
      { type: 'ift', label: 'ift Rosenheim zertifiziert' },
      { type: 'ce', label: 'CE-zertifiziert' },
    ],
    variants: [
      { name: 'Weiss Glatt', color: '#ffffff', border: '#d1d5db', profile: '150×02 / 150×20' },
      { name: 'Golden Eiche', color: '#8B5E2A', border: '#8B5E2A', profile: '150×02 / 150×20' },
      { name: 'Anthrazit Sandgrau', color: '#6B7280', border: '#6B7280', profile: '150×02 / 150×20' },
      { name: 'Sandgrauer Quarz', color: '#9CA3AF', border: '#9CA3AF', profile: '150×02 / 150×20' },
      { name: 'Jetblack Tiefschwarz', color: '#111827', border: '#111827', profile: '150×02 / 150×20' },
    ],
  },

  // ── HEBE-SCHIEBE ────────────────────────────────────────────────────────────

  {
    id: 'hst',
    name: 'HST Hebeschiebetür',
    tagline: 'Panoramablick ohne Kompromisse',
    category: 'Hebe-Schiebe',
    badge: 'Passivhaus',
    image: 'images/produkt-6-hst.png',
    gallery: [
      'images/produkt-6-hst.png',
      'images/produkt-6-hst-2.png',
    ],
    shortDesc: 'Die HST Hebeschiebetür bietet komfortable Verbindung zwischen Innen und Terrasse. Passivhaus-geeignet, Breiten bis 6,50 m, flache Schwelle.',
    description: 'Die Verwendung von HST-Hebeschiebetüren bietet eine ideale Lösung für alle, die eine komfortable Verbindung zwischen Innenraum und Terrasse wünschen und gleichzeitig von einem Panoramablick durch großzügige Glasflächen profitieren möchten. HST-Terrassentüren zeichnen sich durch ihre großzügigen Abmessungen aus, die die Herstellung von Verglasungen mit einer Breite von bis zu sechseinhalb Metern ermöglichen.\n\nDieses System ermöglicht die Konstruktion von Türen in erweiterten Abmessungen. Innerhalb dieses Systems kann die Breite dieser Türen beeindruckende 6,5 Meter erreichen. Dank spezieller Mechanismen lassen sich diese mühelos verschieben. HST-Türen sind zudem mit einer flachen Schwelle ausgestattet, und auf Wunsch des Kunden kann eine spezielle Bremse hinzugefügt werden.',
    specs: [
      { label: 'Uw-Wert', value: '0,71* W/m²K' },
      { label: 'Tauglich', value: 'Passivhaus' },
      { label: 'Bautiefe', value: '70 mm' },
      { label: 'Rahmentiefe', value: '85 mm' },
      { label: 'Max. Höhe', value: '2.700 mm' },
      { label: 'Max. Breite', value: '6.500 mm' },
      { label: 'Dekore', value: '38 Sorten' },
      { label: 'Zertifizierung', value: 'CE' },
    ],
    specsNote: '* Der Uw-Wert für eine Hebe-Schiebe-Tür HST Premium mit den Maßen 4000×2300 mm und einer Verglasung mit einem Ug-Wert von 0,5 W/m²K beträgt 0,71 W/m²K.',
    features: [
      'Passivhaus-geeignet',
      'Breiten bis 6.500 mm, Höhen bis 2.700 mm',
      'Bautiefe 70 mm, Rahmentiefe 85 mm',
      'Flache barrierefreie Schwelle',
      'Mühelos verschiebbar dank spezieller Mechanismen',
      'Optionale Bremse auf Kundenwunsch',
      '38 Dekorfolien',
      'CE-zertifiziert',
    ],
    badges: [
      { type: 'passivhaus', label: 'Passivhaus' },
      { type: 'ce', label: 'CE-zertifiziert' },
    ],
    variants: [
      { name: 'HST Premium', color: '#ffffff', border: '#d1d5db', profile: '' },
      { name: 'HST Basic', color: '#f3f4f6', border: '#d1d5db', profile: '' },
      { name: 'HST 85 Fixframe', color: '#e5e7eb', border: '#d1d5db', profile: '' },
    ],
  },

  {
    id: 'psk',
    name: 'PSK Smart Slide Neo',
    tagline: 'Parallel-Schiebe-Kipp auf neuem Level',
    category: 'Hebe-Schiebe',
    badge: 'Neuheit',
    image: 'images/produkt-7-psk.png',
    gallery: [
      'images/produkt-7-psk.png',
      'images/produkt-7-psk-2.png',
      'images/produkt-7-psk-3.png',
      'images/produkt-7-psk-4.png',
    ],
    shortDesc: 'Terrassentüren im Schiebesystem für großflächige Verglasungen bei voller Wärmedämmung. Leichte Bedienung unabhängig von Größe und Gewicht.',
    description: 'Terrassentüren im Schiebesystem ermöglichen die Schaffung großflächiger Verglasungen, wobei gleichzeitig die volle Wärmedämmung erhalten bleibt. Unabhängig von ihrer Größe und ihrem Gewicht arbeiten die Terrassentüren im Schiebe- und Kipp-Schiebe-System effizient und sind leicht zu bedienen.\n\nDer Smart Slide Neo benötigt wenig Raum und ermöglicht die Schaffung einer breiten Durchgangsöffnung zur Terrasse. Wenn die Tür geschlossen ist, bilden der Schiebeflügel und der Festflügel eine ästhetische Linie. Die Tür verfügt über eine moderne und breite Schwelle, die vielfältige Anwendungsmöglichkeiten bietet, auch im Bereich der Renovierung.\n\nDie Variante PATIO eignet sich mit ihrer traditionellen Schwelle ideal für klassische Balkontüren.',
    specs: [
      { label: 'Bautiefe (Neo)', value: '78 mm' },
      { label: 'Rahmentiefe (Neo)', value: '154 mm' },
      { label: 'Max. Höhe (Neo)', value: '6.000 mm' },
      { label: 'Max. Breite (Neo)', value: '2.500 mm' },
      { label: 'Bautiefe (Patio)', value: '85 mm' },
      { label: 'Max. Höhe (Patio)', value: '2.300 mm' },
      { label: 'Max. Breite (Patio)', value: '1.400 mm' },
    ],
    features: [
      'Parallel-Schiebe-Kipp-Funktion',
      'Smart Slide Neo: max. 6.000 mm Höhe, 2.500 mm Breite',
      'Moderne breite Schwelle (Neo) – ideal für Renovierung',
      'Patio: klassische Schwelle für Balkontüren',
      'Schiebeflügel und Festflügel bilden ästhetische Linie',
      'Leichte Bedienung unabhängig von Größe und Gewicht',
    ],
    badges: [
      { type: 'ce', label: 'CE-zertifiziert' },
    ],
    variants: [
      { name: 'Smart Slide Neo', color: '#ffffff', border: '#d1d5db', profile: '78 mm / 154 mm Rahmen', image: 'images/produkt-7-psk.png' },
      { name: 'Patio', color: '#3C3C3C', border: '#3C3C3C', profile: '85 mm Bautiefe', image: 'images/produkt-7-psk-2.png' },
    ],
  },

  // ── HAUSTÜREN ────────────────────────────────────────────────────────────────

  {
    id: 'eingangstuer-pvc',
    name: 'Eingangstür PVC',
    tagline: 'Sicherheit, Langlebigkeit und Eleganz',
    category: 'Haustür',
    badge: 'Beliebt',
    image: 'images/produkt-8-eingangstuer-pvc.png',
    imageContain: true,
    gallery: [
      'images/produkt-8-eingangstuer-pvc.png',
    ],
    shortDesc: 'Die Haustür ist das Aushängeschild des Hauses. PVC-Profile in Premium (85 mm) und Basic (70 mm), vielfältige Paneele, verstärkte Beschläge.',
    description: 'Die Haustür ist das Aushängeschild des Hauses. Bei der Auswahl von PVC-Türen können Sie sich auf Sicherheit, Langlebigkeit und Eleganz verlassen. Starke und robuste PVC-Profile bilden die Grundlage für eine breite Palette von Paneelen, sowohl modern als auch traditionell. Verstärkte Beschläge gewährleisten langanhaltenden Nutzungskomfort.\n\nDas Profil ist in zwei Ausführungen erhältlich: PREMIUM IDEAL 7000 mit 85 mm Bautiefe für höchste Ansprüche, sowie BASIC IDEAL 4000 mit 70 mm Bautiefe als solide Einstiegslösung.\n\nDrei Füllungsvarianten stehen zur Auswahl: Beidseitige Aufsatzfüllung, Einseitige Aufsatzfüllung und Standard Einsatzfüllung – für jede Gestaltungsanforderung die passende Lösung.',
    specs: [
      { label: 'Profil Premium', value: 'IDEAL 7000 – 85 mm' },
      { label: 'Profil Basic', value: 'IDEAL 4000 – 70 mm' },
      { label: 'Füllung', value: '3 Varianten' },
      { label: 'Beschläge', value: 'Verstärkt' },
      { label: 'Material', value: 'PVC' },
    ],
    features: [
      'Premium IDEAL 7000 Profil (85 mm)',
      'Basic IDEAL 4000 Profil (70 mm)',
      'Beidseitige Aufsatzfüllung',
      'Einseitige Aufsatzfüllung',
      'Standard Einsatzfüllung',
      'Verstärkte Beschläge',
      'Modern und traditionell verfügbar',
    ],
    badges: [
      { type: 'ce', label: 'CE-zertifiziert' },
    ],
    variants: [
      { name: 'Premium IDEAL 7000', color: '#ffffff', border: '#d1d5db', profile: '85 mm' },
      { name: 'Basic IDEAL 4000', color: '#f3f4f6', border: '#d1d5db', profile: '70 mm' },
    ],
  },

  {
    id: 'alu-schiebe',
    name: 'Ziehgriffe',
    tagline: 'Design-Türgriffe für Haustüren & Eingänge',
    category: 'Zubehör',
    badge: 'Neuheit',
    image: 'images/ziehgriffe.png',
    imageContain: true,
    gallery: ['images/ziehgriffe.png'],
    shortDesc: 'Hochwertige Ziehgriffe in verschiedenen Designs – von schlicht bis architektonisch, für Haustüren, Eingänge und Schiebetüren.',
    description: 'Unsere Ziehgriffe verbinden Funktion mit Design und setzen an jeder Tür einen markanten Akzent. Das Sortiment umfasst zwölf Modelle in unterschiedlichen Formen und Oberflächen – von schlanken Rundprofilen bis zu eckigen Designgriffen.\n\nVerfügbare Modelle: Z2 B30, Z6 B30, Z8, Z2 40, Z2 30, Z2 K30, Z2 B40, Z6 BB30, Z27 40X20, Z32, Z43, Z6 W30.\n\nAlle Griffe sind aus hochwertigem Stahl gefertigt und in verschiedenen Oberflächen erhältlich – Schwarz matt, Edelstahl gebürstet und Weiß. Passend für alle gängigen Haustür- und Eingangstürsysteme.',
    specs: [
      { label: 'Material', value: 'Stahl / Edelstahl' },
      { label: 'Oberflächen', value: 'Schwarz, Edelstahl, Weiß' },
      { label: 'Modelle', value: '12 Varianten' },
      { label: 'Passend für', value: 'Haustüren, Eingänge' },
    ],
    features: [
      '12 verschiedene Griffmodelle',
      'Oberflächen: Schwarz matt, Edelstahl, Weiß',
      'Passend für alle gängigen Türsysteme',
      'Schlichte und architektonische Designs',
      'Auf Anfrage auch Sondermaße',
    ],
  },

  // ── ALUMINIUM ────────────────────────────────────────────────────────────────

  {
    id: 'alu-thermo',
    name: 'THERMO Alu – MB 104 Passive',
    tagline: 'Aluminium mit Passivhaus-Standard',
    category: 'Aluminium',
    badge: 'Premium',
    image: 'images/mirox-alu-thermo.jpg',
    shortDesc: 'Dreifach-Isolierglas, Passivhaus-geeignet – für Projekte mit maximalen Anforderungen an Energieeffizienz.',
    description: 'Das MB 104 Passive ist das Spitzenprodukt im MIROX-Aluminiumsortiment. Es kombiniert die Robustheit und Gestaltungsfreiheit von Aluminium mit den Energiewerten eines Passivhausfensters.\n\nDreifach-Isolierglas und die hochwertige Wärmedämmung des Profils machen dieses System zur ersten Wahl für Architekten und Bauherren, die bei Aluminiumprojekten keine Kompromisse beim Energiestandard eingehen.\n\nIndividuell in allen RAL-Farben lackierbar – auch in Zweifarb-Ausführung für unterschiedliche Innen- und Außengestaltung.',
    specs: [
      { label: 'Material', value: 'Aluminium' },
      { label: 'Verglasung', value: '3-fach' },
      { label: 'Standard', value: 'Passivhaus' },
      { label: 'Einbruchschutz', value: 'RC2' },
      { label: 'Lackierung', value: 'RAL nach Wahl' },
      { label: 'Ausführung', value: 'Einfarb / Zweifarb' },
    ],
    features: [
      'Passivhaus-geeignet',
      'Dreifach-Isolierglas',
      'Einbruchschutz RC2',
      'RAL-Lackierung, auch Zweifarb',
      'Maximale Gestaltungsfreiheit',
    ],
  },

  {
    id: 'alu-ferroline',
    name: 'NEW DESIGN – Ferroline',
    tagline: 'Loft-Ästhetik aus Aluminium',
    category: 'Aluminium',
    image: 'images/mirox-alu-design.jpg',
    shortDesc: 'Stahlkonstruktionen imitierendes Loft-Fenster. Maximale Glasfläche bei minimaler Profilbreite.',
    description: 'Das Ferroline-System aus der NEW DESIGN Serie imitiert die Optik klassischer Stahlkonstruktionen und verbindet industrielle Ästhetik mit moderner Aluminium-Technologie.\n\nDas Slim-Profil maximiert den Glasanteil und schafft spektakuläre Fassadenansichten. Ideal für Loft-Projekte, Umbauten historischer Gebäude und zeitgenössische Architektur, die auf den charakteristischen Industrielook setzt.\n\nAuf Wunsch in allen RAL-Farben verfügbar – auch in klassischem Schwarz für die authentische Stahloptik.',
    specs: [
      { label: 'Material', value: 'Aluminium' },
      { label: 'Design', value: 'Loft / Stahloptik' },
      { label: 'Profil', value: 'Slim' },
      { label: 'Lackierung', value: 'RAL nach Wahl' },
    ],
    features: [
      'Authentische Stahloptik',
      'Maximale Glasfläche',
      'Slim-Profil für moderne Ästhetik',
      'RAL-Lackierung nach Wahl',
      'Ideal für Loft und Industriedesign',
    ],
  },

  {
    id: 'alu-harmonika',
    name: 'Alu Falttür – Harmonika',
    tagline: 'Terrassenübergang ohne Grenzen',
    category: 'Aluminium',
    badge: 'Terrasse',
    image: 'images/mirox-alu-falt.jpg',
    shortDesc: 'Falttüren aus wärmegedämmten Aluminiumprofilen – nach innen oder außen öffnend, CE-zertifiziert.',
    description: 'Die Alu Falttür Harmonika schafft den fließenden Übergang zwischen Wohnraum und Außenbereich. Beim vollständigen Öffnen falten sich die Flügel platzsparend zur Seite und geben die gesamte Öffnungsbreite frei.\n\nDie wärmegedämmten Aluminiumprofile können nach innen oder außen öffnend konfiguriert werden. In Verbindung mit der CE-Zertifizierung und der vollständigen RAL-Lackierbarkeit bietet die Harmonika maximale Gestaltungsfreiheit.\n\nIdeal für Terrassen, Wintergärten und repräsentative Übergänge in Wohn- und Gewerbeprojekten.',
    specs: [
      { label: 'Material', value: 'Aluminium' },
      { label: 'Öffnungsrichtung', value: 'Innen / Außen' },
      { label: 'Zertifizierung', value: 'CE' },
      { label: 'Lackierung', value: 'RAL vollständig' },
    ],
    features: [
      'Vollständige Öffnung der Fassade',
      'Nach innen oder außen öffnend',
      'Wärmegedämmte Aluminiumprofile',
      'CE-zertifiziert',
      'Vollständig RAL-lackierbar',
    ],
  },

  // ── HAUSTÜREN ────────────────────────────────────────────────────────────────

  {
    id: 'haustuer-pvc',
    name: 'Haustür Modern – PVC',
    tagline: 'Moderner Eingang aus Kunststoff',
    category: 'Haustür',
    badge: 'Modern',
    image: 'images/mirox-pvc-haustuer.jpg',
    shortDesc: 'Moderne Kunststoff-Haustüren auf IDEAL 7000-Basis. Verstärkte Beschläge, breite Auswahl an modernen Paneelen.',
    description: 'Die Haustür Modern PVC basiert auf dem bewährten IDEAL 7000-Profil und kombiniert höchste Energieeffizienz mit zeitlosem Design. Die verstärkten Beschläge sorgen für lange Haltbarkeit und hohe Sicherheit.\n\nEine breite Auswahl an modernen und klassischen Türpaneelen erlaubt die individuelle Gestaltung des Eingangsbereichs. Ob klare geometrische Formen oder elegante Glasfelder – die Haustür Modern PVC lässt sich perfekt an den Baustil des Gebäudes anpassen.\n\nAuf Basis des IDEAL 7000-Profils mit 85 mm Bautiefe und Einbruchschutz RC2.',
    specs: [
      { label: 'Profil', value: 'IDEAL 7000' },
      { label: 'Bautiefe', value: '85 mm' },
      { label: 'Einbruchschutz', value: 'RC2' },
      { label: 'Material', value: 'Kunststoff (PVC)' },
      { label: 'Paneel-Auswahl', value: 'Groß' },
    ],
    features: [
      'Basis: IDEAL 7000 Profil',
      '85 mm Bautiefe',
      'Einbruchschutz RC2',
      'Breite Paneel-Auswahl',
      'Klassisch und modern konfigurierbar',
    ],
  },

  {
    id: 'haustuer-genesis',
    name: 'Alu Haustür – Genesis 75',
    tagline: 'Repräsentativer Aluminium-Eingang',
    category: 'Haustür',
    badge: 'RC2',
    image: 'images/mirox-alu-haustuer.jpg',
    shortDesc: 'Repräsentative Aluminium-Eingangstür mit hoher Festigkeit. RC2-Einbruchschutz, individuell in RAL-Farben.',
    description: 'Die Genesis 75 steht für repräsentative Aluminium-Haustüren, die höchste Sicherheitsansprüche mit außergewöhnlichem Design verbinden. Zertifizierter Einbruchschutz der Klasse RC2 schützt zuverlässig vor ungebetenen Gästen.\n\nDie hohe Profilstabilität und die Langlebigkeit von Aluminium machen die Genesis 75 zur dauerhaften Investition. Individuell in allen RAL-Farben konfigurierbar – auch in Zweifarb-Ausführung für unterschiedliche Innen- und Außengestaltung.\n\nIdeal für Einfamilienhäuser, Mehrfamilienhäuser und repräsentative Geschäftseingänge.',
    specs: [
      { label: 'Material', value: 'Aluminium' },
      { label: 'Einbruchschutz', value: 'RC2' },
      { label: 'Lackierung', value: 'RAL nach Wahl' },
      { label: 'Ausführung', value: 'Einfarb / Zweifarb' },
    ],
    features: [
      'Einbruchschutz Klasse RC2',
      'Hochfestes Aluminiumprofil',
      'RAL-Lackierung nach Wahl',
      'Zweifarb-Ausführung möglich',
      'Für privat und gewerblich',
    ],
  },

];
